
/**
    @addtogroup DoremirStringList

    Provides conversions between \ref String and \ref List.
    
    This functionality should to be in the String module, but unfortunately that would create a recursive
    dependency between \ref DoremirString and \ref DoremirList.

 */
module Doremir.String.List
{                          
    import Doremir.String;
    import Doremir.List;
    
    convert : String -> List;
    unconvert : List -> String;
}