
/** 
    Provides lifting of binary functions into audio processors.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `()`
    Argument       | `()`
    Result         | `()`
    Input          | `(a,b)`
    Output         | `c`

    @defgroup   DoremirAudioProcessorBinary Audio processors: Binary
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Binary
{
    
}