

/** 
    Delays an audio signal.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `()`
    Argument       | `time`
    Result         | `()`
    Input          | `a`
    Output         | `a`
    
    @defgroup   DoremirAudioProcessorDelay Audio processors: Delay
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Delay
{
    
}