
/** 
    Provides the primitive delay processor.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `a`
    Argument       | `()`
    Result         | `()`
    Input          | `a`
    Output         | `a`
    
    @defgroup   DoremirAudioProcessorDelay Audio processors: Delay
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Delay
{
    
}