
/** 
    Provides recursive composition of audio processors.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `c`
    Argument       | `()`
    Result         | `()`
    Input          | `a`
    Output         | `b`
    
    
    @defgroup   DoremirAudioProcessorLoop Audio processors: Loop
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Loop
{
    
}