
/**
    Provides parallel composition of audio processors.
    
    ### Associated types

    Given audio processors *a* and *b*, *f ||| g* has the following properties:

    Kind           | Type
    -------------- | --------------------------
    State          | `(state a, state b)`
    Argument       | `(argument a, argument b)`
    Result         | `(result a, result b)`
    Input          | `(input a, input b)`
    Output         | `(output a, output b)`

    @defgroup   DoremirAudioProcessorParallel Audio processors: Parallel
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Parallel
{

}