
/** 
    Splits an audio signal.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `()`
    Argument       | `()`
    Result         | `()`
    Input          | `a`
    Output         | `(a,a)`

    @defgroup   DoremirAudioProcessorSplit Audio processors: Split
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Split
{
    
}