
/** 
    Provides lifting of ternary functions into audio processors.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `()`
    Argument       | `()`
    Result         | `()`
    Input          | `(a,b,c)`
    Output         | `d`
    
    @defgroup   DoremirAudioProcessorTernary Audio processors: Ternary
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Ternary
{
    
}