
/** 
    Provides lifting of ternary functions into audio processors.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `()`
    Argument       | `()`
    Result         | `()`
    Input          | `(a,b,c)`
    Output         | `d`
    
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Ternary
{
    type Func = Intptr;
    type Proc = Intptr;    
    lift : (Func) -> Proc;   
}