
/** 
    Provides lifting of unary functions into audio processors.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `()`
    Argument       | `()`
    Result         | `()`
    Input          | `a`
    Output         | `b`
    
    @defgroup   DoremirAudioProcessorUnary Audio processors: Unary
    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Unary
{
    type Func = Intptr;
    type Proc = Intptr;    
    lift : (Func) -> Proc;   
}