
/**
    Provides atomic variables
    
    @defgroup   DoremirAtomic Concurrency: Atomic variables
    @author     Hans Höglund
 */
module Doremir.Atomic
{
    type Atomic = Intptr;
    type Updater = (Intptr) -> Intptr;
    
    create  : () -> Atomic;
    copy    : (Atomic) -> Atomic;
    swap    : (Atomic, Atomic) -> Void;
    destroy : (Atomic) -> Void;
    
    get : (Atomic) -> Intptr;
    set : (Atomic, Intptr) -> Void;
    modify : (Atomic, Updater) -> Void;
}

