
/**
    Basic definitions. 
 */
module Fa
{
    import Fa.Std;

    import "C" Fa.Alloc;
    import "C" Fa.Interfaces;


    // Basic types

    /** Pointer type, equivalent to `void*`.
    */
    type Ptr = Void*;

    // Function types

    /** A nullary function, defined as `fa_ptr_t(*fa_nullary_t )(fa_ptr_t)`.

        The first argument is an environment pointer which is usually passed along with the function.
        This is the standard C technique for closing over variables.
    */
    type Nullary = (Ptr -> Ptr)*;

    /** A unary function.

        The first argument is an environment pointer which is usually passed along with the function.
        This is the standard C technique for closing over variables.
    */
    type Unary   = ((Ptr, Ptr) -> Ptr)*;

    /** A binary function.

        The first argument is an environment pointer which is usually passed along with the function.
        This is the standard C technique for closing over variables.
    */
    type Binary  = ((Ptr, Ptr, Ptr) -> Ptr)*;

    /** A ternary function.

        The first argument is an environment pointer which is usually passed along with the function.
        This is the standard C technique for closing over variables.
    */
    type Ternary  = ((Ptr, Ptr, Ptr, Ptr) -> Ptr)*;

    /** A predicate, or boolean function.

        The first argument is an environment pointer which is usually passed along with the function.
        This is the standard C technique for closing over variables.
    */
    type Pred   = ((Ptr, Ptr) -> Bool)*;

    /** A predicate used for testing an object for deep destruction.
    */
    type DeepDestroyPred  = (Ptr -> Bool)*;


    // Character types

    /** An 8-bit character. */
    type Char8  = Char;
    /** A 16-bit character. */
    type Char16 = UInt16;
    /** A 32-bit character. */
    type Char32 = UInt32;


    // Type predicates and conversions
    // TODO move to dynamic (se #158)

    /** Return whether the given value is referecing a @bool@. 
        @see [Value references](@ref ValueReferences) */
    isBool     : Ptr -> Bool;

    /** Return whether the given value is referecing a @int8_t@. 
        @see [Value references](@ref ValueReferences) */
    isInt8     : Ptr -> Bool;

    /** Return whether the given value is referecing a @int16_t@. 
        @see [Value references](@ref ValueReferences) */
    isInt16    : Ptr -> Bool;

    /** Return whether the given value is referecing a @int32_t@. 
        @see [Value references](@ref ValueReferences) */
    isInt32    : Ptr -> Bool;

    /** Return whether the given value is referecing a @int64_t@. 
        @see [Value references](@ref ValueReferences) */
    isInt64    : Ptr -> Bool;

    /** Return whether the given value is referecing a @float@. 
        @see [Value references](@ref ValueReferences) */
    isFloat    : Ptr -> Bool;

    /** Return whether the given value is referecing a @double@. 
        @see [Value references](@ref ValueReferences) */
    isDouble   : Ptr -> Bool;

    /** Return whether the given value is a reference ("object") type. 
        @see [Value references](@ref ValueReferences) */
    isRef      : Ptr -> Bool;
    
    /** Return whether the given value is of an integer type (int8, int16, int32 or int64).
        @see [Value references](@ref ValueReferences) */
    isInteger  : Ptr -> Bool;

    /** Return whether the given value is of a numeric type (int8, int16, int32, int64, float or double).
        @see [Value references](@ref ValueReferences) */
    isNumber   : Ptr -> Bool;

    /** Unwrap a referece to a @bool@ and destroy the reference. 
        @see [Value references](@ref ValueReferences) */
    toBool     : Ptr -> Bool;

    /** Unwrap a referece to a @int8_t@ and destroy the reference. 
        @see [Value references](@ref ValueReferences) */
    toInt8     : Ptr -> Int8;

    /** Unwrap a referece to a @int16_t@ and destroy the reference. 
        @see [Value references](@ref ValueReferences) */
    toInt16    : Ptr -> Int16;

    /** Unwrap a referece to a @int32_t@ and destroy the reference. 
        @see [Value references](@ref ValueReferences) */
    toInt32    : Ptr -> Int32;

    /** Unwrap a referece to a @int64_t@ and destroy the reference. 
        @see [Value references](@ref ValueReferences) */
    toInt64    : Ptr -> Int64;

    /** Unwrap a referece to a @float@ and destroy the reference. 
        @see [Value references](@ref ValueReferences) */
    toFloat    : Ptr -> Float;

    /** Unwrap a referece to a @double@ and destroy the reference. 
        @see [Value references](@ref ValueReferences) */
    toDouble   : Ptr -> Double;

    /** Unwrap a referece to a @bool@ without destroying the reference. 
        @see [Value references](@ref ValueReferences) */
    peekBool     : Ptr -> Bool;

    /** Unwrap a referece to a @int8_t@ without destroying the reference. 
        @see [Value references](@ref ValueReferences) */
    peekInt8     : Ptr -> Int8;

    /** Unwrap a referece to a @int16_t@ without destroying the reference. 
        @see [Value references](@ref ValueReferences) */
    peekInt16    : Ptr -> Int16;

    /** Unwrap a referece to a @int32_t@ without destroying the reference. 
        @see [Value references](@ref ValueReferences) */
    peekInt32    : Ptr -> Int32;

    /** Unwrap a referece to a @int64_t@ without destroying the reference. 
        @see [Value references](@ref ValueReferences) */
    peekInt64    : Ptr -> Int64;

    /** Unwrap a referece to a @float@ without destroying the reference. 
        @see [Value references](@ref ValueReferences) */
    peekFloat    : Ptr -> Float;

    /** Unwrap a referece to a @double@ without destroying the reference. 
        @see [Value references](@ref ValueReferences) */
    peekDouble   : Ptr -> Double;
    
    /** Unwrap a referece to an integer (int8, int16, int32 or int64) without destroying the reference.
        The result is promoted to an int64.
        @see [Value references](@ref ValueReferences) 
    */
    peekInteger  : Ptr -> Int64;

    /** Unwrap a referece to a number (int8, int16, int32, int64, float or double) without destroying the reference.
        The result is promoted to a double.
        @see [Value references](@ref ValueReferences) 
    */
    peekNumber   : Ptr -> Double;

    /** Create a new referece to a @bool@ value.
        The returned reference must be destroyed by the caller.
        @see [Value references](@ref ValueReferences) */
    fromBool   : Bool -> Ptr;

    /** Create a new referece to a @int8_t@ value.
        The returned reference must be destroyed by the caller.
        @see [Value references](@ref ValueReferences) */
    fromInt8   : Int8 -> Ptr;

    /** Create a new referece to a @int16_t@ value.
        The returned reference must be destroyed by the caller.
        @see [Value references](@ref ValueReferences) */
    fromInt16  : Int16 -> Ptr;

    /** Create a new referece to a @int32_t@ value.
        The returned reference must be destroyed by the caller.
        @see [Value references](@ref ValueReferences) */
    fromInt32  : Int32 -> Ptr;

    /** Create a new referece to a @int64_t@ value.
        The returned reference must be destroyed by the caller.
        @see [Value references](@ref ValueReferences) */
    fromInt64  : Int64 -> Ptr;

    /** Create a new referece to a @float@ value.
        The returned reference must be destroyed by the caller.
        @see [Value references](@ref ValueReferences) */
    fromFloat  : Float -> Ptr;

    /** Create a new referece to a @double@ value.
        The returned reference must be destroyed by the caller.
        @see [Value references](@ref ValueReferences) */
    fromDouble : Double -> Ptr;
    

    // Interface dispatch

    /** Unique identifier. Only used for interface lookup at the moment.
    */
    type Id = Int64;

    /** Callback to lookup an interface implementation.
    */
    type Impl = (Id -> Ptr)*;

    /** Returns an implenentation of the given interface on the given value.
        @return Pointer to implementation (optional).
        @see [Interfaces](@ref Interfaces)
      */
    interface : (Id, Ptr) -> Ptr;


    // Interfaces

    /** Equality comparison interface.
    */
    type Equal   = struct {
        equal : ((Ptr, Ptr) -> Bool)*
    };

    /** Return whether the given values are equal.
        @see [Equal](@ref fa_equal_t)
        
        @note
          * NULL == NULL
          * Identical pointers return true, regardless of type (this means that non-wrapped values may be passed to fa_equal)
          * Numerical values are compared numerically (regardless of the underlying number type)
          * Other values will generally have to be the same type, unless overridden by their implementation of fa_equal_t
      */
    equal            : (Ptr, Ptr) -> Bool;
    
    /** Return whether the given values are unequal.
        @see [Equal](@ref fa_equal_t)
      */
    notEqual         : (Ptr, Ptr) -> Bool;
    
    /** Identical to @ref fa_equal, but destroys both arguments (unless they are NULL).
        @see [Equal](@ref fa_equal_t)
        @see @ref fa_equal
    */
    dequal            : (Ptr, Ptr) -> Bool;

    /** Less-than comparison interface.
    */
    type Order  = struct {
        lessThan    : ((Ptr, Ptr) -> Bool)*,
        greaterThan : ((Ptr, Ptr) -> Bool)*
    };

    lessThan         : (Ptr, Ptr) -> Bool;
    greaterThan      : (Ptr, Ptr) -> Bool;
    lessThanEqual    : (Ptr, Ptr) -> Bool;
    greaterThanEqual : (Ptr, Ptr) -> Bool;
    min              : (Ptr, Ptr) -> Ptr;
    max              : (Ptr, Ptr) -> Ptr;

    /** Arithmetic operations interface.
    */
    type Number = struct {
        add      : ((Ptr, Ptr) -> Ptr)*,
        subtract : ((Ptr, Ptr) -> Ptr)*,
        multiply : ((Ptr, Ptr) -> Ptr)*,
        divide   : ((Ptr, Ptr) -> Ptr)*,
        absolute : (Ptr -> Ptr)*
    };

    add         : (Ptr, Ptr) -> Ptr;
    subtract    : (Ptr, Ptr) -> Ptr;
    multiply    : (Ptr, Ptr) -> Ptr;
    divide      : (Ptr, Ptr) -> Ptr;
    absolute    : Ptr -> Ptr;
    dadd         : (Ptr, Ptr) -> Ptr;
    dsubtract    : (Ptr, Ptr) -> Ptr;
    dmultiply    : (Ptr, Ptr) -> Ptr;
    ddivide      : (Ptr, Ptr) -> Ptr;
    dabsolute    : Ptr -> Ptr;

    /** Generic copying interface.
    */
    type Copy   = struct {
        copy : (Ptr -> Ptr)*,
        deepCopy : (Ptr -> Ptr)*
    };

    /** Generic destruction interface.
    */
    type Destroy   = struct {
        destroy : (Ptr -> Void)*,
        deepDestroy : ((Ptr, DeepDestroyPred) -> Void)*
    };

    /** Copy the given value.
        @see [Copy](@ref fa_copy_t)
      */
    copy    : Ptr -> Ptr;
    
    /** Deep copy the given value.
        @see [Copy](@ref fa_deep_t)
      
    */
    deepCopy : Ptr -> Ptr;
    
    /** Move the given value. This is the identity function,
        just serves as a notification.
      */
    move    : Ptr -> Ptr;
    
    /** Destroy the given value.
        @param  Value to destroy (destroyed).
        @see [Destroy](@ref fa_destroy_t)
      */
    destroy : Ptr -> Void;

    /** Destroy the given value and contained values (in case of a collection such as a pair or list).
        @param  Value to destroy (destroyed).
        @param  Predicate function
        @see [Destroy](@ref fa_destroy_t)
      */
    deepDestroy : (Ptr, DeepDestroyPred) -> Void;
    
    deepDestroyAlways : Ptr -> Void;

    /** Generic append operation interface. */
    type Semigroup = struct {
        append : ((Ptr, Ptr) -> Ptr)*
    };

    /** Generic empty value interface. */
    type Monoid = struct {
        empty : ((dummy : Ptr) -> Ptr)*
    };

    append : (Ptr, Ptr) -> Ptr;
    dappend : (Ptr, Ptr) -> Ptr;
    
    empty : Ptr -> Ptr;

    /** Return whether the given value is an error or not.

        This function is often used with [log](@ref fa_error_log) as in:

        ~~~
        if (fa_check(value)) {
            fa_error_log(NULL, value);
            exit(-1);
        }
        ~~~

        @param value Value to check (can be any type).
        @return
          A boolean.
     */
    check   : Ptr -> Bool;

    /** Print the given value, using [Show](@ref fa_string_show_t).
        @param format   A printf-style format string.
        @param value    Value to print.
      */
    print    : (Char*,Ptr) -> Void;
    dprint   : (Char*,Ptr) -> Void;
    printLn  : (Ptr) -> Void;
    dprintLn : (Ptr) -> Void;
}

