
all:	gen

gen:
	modulo --language=c    <modules/Atomic.module    		>inc/doremir/atomic.h; \
	modulo --language=c    <modules/Atomic/Queue.module       	>inc/doremir/atomic/queue.h; \
	modulo --language=c    <modules/Atomic/Stack.module       	>inc/doremir/atomic/stack.h; \
	modulo --language=c    <modules/Atomic/RingBuffer.module  	>inc/doremir/atomic/ring_buffer.h; \
	modulo --language=c    <modules/Thread.module    		>inc/doremir/thread.h;
	modulo --language=c    <modules/Thread/Future.module    	>inc/doremir/thread/future.h;
	modulo --language=c    <modules/Thread/Improving.module    	>inc/doremir/thread/improving.h;
                                                                                          
	modulo --language=c    <modules/Ratio.module    		>inc/doremir/ratio.h;
	modulo --language=c    <modules/Chase.module    		>inc/doremir/chase.h;
	modulo --language=c    <modules/List.module    			>inc/doremir/list.h; 
	modulo --language=c    <modules/Set.module    			>inc/doremir/set.h;  
	modulo --language=c    <modules/Pair.module    			>inc/doremir/pair.h; 
	modulo --language=c    <modules/Map.module    			>inc/doremir/map.h;  
	modulo --language=c    <modules/PriorityQueue.module		>inc/doremir/priority_queue.h;  
                                                                                          
	modulo --language=c    <modules/Midi.module    			>inc/doremir/midi.h;
	modulo --language=c    <modules/Audio.module    		>inc/doremir/audio.h;

	modulo --language=c    <modules/Audio/Time.module    		>inc/doremir/audio/time.h;
                                                                                         
	modulo --language=c    <modules/Audio/Processor.module  	>inc/doremir/audio/processor.h;
	modulo --language=c    <modules/Audio/Processor/Unary.module  	>inc/doremir/audio/processor/unary.h;
	modulo --language=c    <modules/Audio/Processor/Binary.module  	>inc/doremir/audio/processor/binary.h;
	modulo --language=c    <modules/Audio/Processor/Ternary.module  >inc/doremir/audio/processor/ternary.h;
	modulo --language=c    <modules/Audio/Processor/Delay.module  	>inc/doremir/audio/processor/split.h;
	modulo --language=c    <modules/Audio/Processor/Split.module  	>inc/doremir/audio/processor/delay.h;
	modulo --language=c    <modules/Audio/Processor/Sequence.module >inc/doremir/audio/processor/sequence.h;
	modulo --language=c    <modules/Audio/Processor/Parallel.module >inc/doremir/audio/processor/parallel.h;
	modulo --language=c    <modules/Audio/Processor/Loop.module	>inc/doremir/audio/processor/loop.h;
                                                                                                   
	modulo --language=c    <modules/Audio/Device.module    		>inc/doremir/audio/device.h;
	modulo --language=c    <modules/Audio/Device/Buffer.module	>inc/doremir/audio/device/buffer.h;
	modulo --language=c    <modules/Audio/Device/File.module    	>inc/doremir/audio/device/file.h;
	modulo --language=c    <modules/Audio/Device/Audio.module    	>inc/doremir/audio/device/audio.h;
	modulo --language=c    <modules/Audio/Device/Midi.module    	>inc/doremir/audio/device/midi.h;
                                                                                                
	modulo --language=c    <modules/Audio/Scheduler.module  	>inc/doremir/audio/scheduler.h;
	modulo --language=c    <modules/Audio/Dispatcher.module 	>inc/doremir/audio/dispatcher.h;





	modulo --language=lisp <modules/Atomic.module    		>lsp/doremir/atomic.lisp; \
	modulo --language=lisp <modules/Atomic/Queue.module       	>lsp/doremir/atomic/queue.lisp; \
	modulo --language=lisp <modules/Atomic/Stack.module       	>lsp/doremir/atomic/stack.lisp; \
	modulo --language=lisp <modules/Atomic/RingBuffer.module  	>lsp/doremir/atomic/ring_buffer.lisp; \
	modulo --language=lisp <modules/Thread.module    		>lsp/doremir/thread.lisp;
	modulo --language=lisp <modules/Thread/Future.module    	>lsp/doremir/thread/future.lisp;
	modulo --language=lisp <modules/Thread/Improving.module    	>lsp/doremir/thread/improving.lisp;
                                                                                          
	modulo --language=lisp <modules/Ratio.module    		>lsp/doremir/ratio.lisp;
	modulo --language=lisp <modules/Chase.module    		>lsp/doremir/chase.lisp;
	modulo --language=lisp <modules/List.module    			>lsp/doremir/list.lisp; 
	modulo --language=lisp <modules/Set.module    			>lsp/doremir/set.lisp;  
	modulo --language=lisp <modules/Pair.module    			>lsp/doremir/pair.lisp; 
	modulo --language=lisp <modules/Map.module    			>lsp/doremir/map.lisp;  
	modulo --language=lisp <modules/PriorityQueue.module		>lsp/doremir/priority_queue.lisp;  
                                                                                          
	modulo --language=lisp <modules/Midi.module    			>lsp/doremir/midi.lisp;
	modulo --language=lisp <modules/Audio.module    		>lsp/doremir/audio.lisp;

	modulo --language=lisp <modules/Audio/Time.module    		>lsp/doremir/audio/time.lisp;
                                                                                         
	modulo --language=lisp <modules/Audio/Processor.module  	>lsp/doremir/audio/processor.lisp;
	modulo --language=lisp <modules/Audio/Processor/Unary.module  	>lsp/doremir/audio/processor/unary.lisp;
	modulo --language=lisp <modules/Audio/Processor/Binary.module  	>lsp/doremir/audio/processor/binary.lisp;
	modulo --language=lisp <modules/Audio/Processor/Ternary.module  >lsp/doremir/audio/processor/ternary.lisp;
	modulo --language=lisp <modules/Audio/Processor/Delay.module  	>lsp/doremir/audio/processor/split.lisp;
	modulo --language=lisp <modules/Audio/Processor/Split.module  	>lsp/doremir/audio/processor/delay.lisp;
	modulo --language=lisp <modules/Audio/Processor/Sequence.module >lsp/doremir/audio/processor/sequence.lisp;
	modulo --language=lisp <modules/Audio/Processor/Parallel.module >lsp/doremir/audio/processor/parallel.lisp;
	modulo --language=lisp <modules/Audio/Processor/Loop.module	>lsp/doremir/audio/processor/loop.lisp;
                                                                                                   
	modulo --language=lisp <modules/Audio/Device.module    		>lsp/doremir/audio/device.lisp;
	modulo --language=lisp <modules/Audio/Device/Buffer.module	>lsp/doremir/audio/device/buffer.lisp;
	modulo --language=lisp <modules/Audio/Device/File.module    	>lsp/doremir/audio/device/file.lisp;
	modulo --language=lisp <modules/Audio/Device/Audio.module    	>lsp/doremir/audio/device/audio.lisp;
	modulo --language=lisp <modules/Audio/Device/Midi.module    	>lsp/doremir/audio/device/midi.lisp;
                                                                                                
	modulo --language=lisp <modules/Audio/Scheduler.module  	>lsp/doremir/audio/scheduler.lisp;
	modulo --language=lisp <modules/Audio/Dispatcher.module 	>lsp/doremir/audio/dispatcher.lisp;
                                                                                         


doc:    gen
	doxygen inc/Doxyfile

clean:
	rm inc/*.h; \
	rm inc/*.lisp;