
/**
    Provides the map data structure. 
    
    @defgroup DoremirMap Data structures: Maps
 */
module Doremir.Map 
{
    type Map = IntPtr;
    type Value = IntPtr;
    
    empty   : () -> Map;
    single  : (Key, Value) -> Map;
    append  : (Map, Map) -> Map;
    destroy : (Map) -> Void;
    copy    : (Map) -> Map;
    swap    : (Map, Map) -> Void;

    key            : (Map, Key) -> Bool;
    elem           : (Map, Value) -> Bool;
    entry          : (Map, Pair) -> Bool;
    submapOf       : (Map, Map) -> Bool;
    properSubmapOf : (Map, Map) -> Bool;

    // TODO what about equality?    
                                
    add           : (Map, Key, Value) -> Map;
    remove        : (Map, Key, Value) -> Void;
    addDest       : (Map, Key, Value) -> Map;
    removeDest    : (Map, Key, Value) -> Void;
}