# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/DoReMIR/faudio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/DoReMIR/faudio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/DoReMIR/faudio/CMakeFiles /Volumes/DoReMIR/faudio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/DoReMIR/faudio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named components_clean

# Build rule for target.
components_clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 components_clean
.PHONY : components_clean

# fast build rule for target.
components_clean/fast:
	$(MAKE) -f CMakeFiles/components_clean.dir/build.make CMakeFiles/components_clean.dir/build
.PHONY : components_clean/fast

#=============================================================================
# Target rules for targets named components_print

# Build rule for target.
components_print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 components_print
.PHONY : components_print

# fast build rule for target.
components_print/fast:
	$(MAKE) -f CMakeFiles/components_print.dir/build.make CMakeFiles/components_print.dir/build
.PHONY : components_print/fast

#=============================================================================
# Target rules for targets named components_resolve

# Build rule for target.
components_resolve: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 components_resolve
.PHONY : components_resolve

# fast build rule for target.
components_resolve/fast:
	$(MAKE) -f CMakeFiles/components_resolve.dir/build.make CMakeFiles/components_resolve.dir/build
.PHONY : components_resolve/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named runsc

# Build rule for target.
runsc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runsc
.PHONY : runsc

# fast build rule for target.
runsc/fast:
	$(MAKE) -f CMakeFiles/runsc.dir/build.make CMakeFiles/runsc.dir/build
.PHONY : runsc/fast

#=============================================================================
# Target rules for targets named faudio_framework

# Build rule for target.
faudio_framework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 faudio_framework
.PHONY : faudio_framework

# fast build rule for target.
faudio_framework/fast:
	$(MAKE) -f shared/CMakeFiles/faudio_framework.dir/build.make shared/CMakeFiles/faudio_framework.dir/build
.PHONY : faudio_framework/fast

#=============================================================================
# Target rules for targets named faudio_tests

# Build rule for target.
faudio_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 faudio_tests
.PHONY : faudio_tests

# fast build rule for target.
faudio_tests/fast:
	$(MAKE) -f test/CMakeFiles/faudio_tests.dir/build.make test/CMakeFiles/faudio_tests.dir/build
.PHONY : faudio_tests/fast

#=============================================================================
# Target rules for targets named custom

# Build rule for target.
custom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom
.PHONY : custom

# fast build rule for target.
custom/fast:
	$(MAKE) -f tools/CMakeFiles/custom.dir/build.make tools/CMakeFiles/custom.dir/build
.PHONY : custom/fast

#=============================================================================
# Target rules for targets named erik

# Build rule for target.
erik: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 erik
.PHONY : erik

# fast build rule for target.
erik/fast:
	$(MAKE) -f tools/CMakeFiles/erik.dir/build.make tools/CMakeFiles/erik.dir/build
.PHONY : erik/fast

#=============================================================================
# Target rules for targets named faudio

# Build rule for target.
faudio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 faudio
.PHONY : faudio

# fast build rule for target.
faudio/fast:
	$(MAKE) -f tools/CMakeFiles/faudio.dir/build.make tools/CMakeFiles/faudio.dir/build
.PHONY : faudio/fast

#=============================================================================
# Target rules for targets named impulses

# Build rule for target.
impulses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 impulses
.PHONY : impulses

# fast build rule for target.
impulses/fast:
	$(MAKE) -f tools/CMakeFiles/impulses.dir/build.make tools/CMakeFiles/impulses.dir/build
.PHONY : impulses/fast

#=============================================================================
# Target rules for targets named io_simple_filter

# Build rule for target.
io_simple_filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io_simple_filter
.PHONY : io_simple_filter

# fast build rule for target.
io_simple_filter/fast:
	$(MAKE) -f tools/CMakeFiles/io_simple_filter.dir/build.make tools/CMakeFiles/io_simple_filter.dir/build
.PHONY : io_simple_filter/fast

#=============================================================================
# Target rules for targets named level

# Build rule for target.
level: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 level
.PHONY : level

# fast build rule for target.
level/fast:
	$(MAKE) -f tools/CMakeFiles/level.dir/build.make tools/CMakeFiles/level.dir/build
.PHONY : level/fast

#=============================================================================
# Target rules for targets named list_audio

# Build rule for target.
list_audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list_audio
.PHONY : list_audio

# fast build rule for target.
list_audio/fast:
	$(MAKE) -f tools/CMakeFiles/list_audio.dir/build.make tools/CMakeFiles/list_audio.dir/build
.PHONY : list_audio/fast

#=============================================================================
# Target rules for targets named list_midi

# Build rule for target.
list_midi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list_midi
.PHONY : list_midi

# fast build rule for target.
list_midi/fast:
	$(MAKE) -f tools/CMakeFiles/list_midi.dir/build.make tools/CMakeFiles/list_midi.dir/build
.PHONY : list_midi/fast

#=============================================================================
# Target rules for targets named play

# Build rule for target.
play: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 play
.PHONY : play

# fast build rule for target.
play/fast:
	$(MAKE) -f tools/CMakeFiles/play.dir/build.make tools/CMakeFiles/play.dir/build
.PHONY : play/fast

#=============================================================================
# Target rules for targets named plug_audio

# Build rule for target.
plug_audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plug_audio
.PHONY : plug_audio

# fast build rule for target.
plug_audio/fast:
	$(MAKE) -f tools/CMakeFiles/plug_audio.dir/build.make tools/CMakeFiles/plug_audio.dir/build
.PHONY : plug_audio/fast

#=============================================================================
# Target rules for targets named plug_midi

# Build rule for target.
plug_midi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plug_midi
.PHONY : plug_midi

# fast build rule for target.
plug_midi/fast:
	$(MAKE) -f tools/CMakeFiles/plug_midi.dir/build.make tools/CMakeFiles/plug_midi.dir/build
.PHONY : plug_midi/fast

#=============================================================================
# Target rules for targets named record

# Build rule for target.
record: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 record
.PHONY : record

# fast build rule for target.
record/fast:
	$(MAKE) -f tools/CMakeFiles/record.dir/build.make tools/CMakeFiles/record.dir/build
.PHONY : record/fast

#=============================================================================
# Target rules for targets named record_streaming

# Build rule for target.
record_streaming: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 record_streaming
.PHONY : record_streaming

# fast build rule for target.
record_streaming/fast:
	$(MAKE) -f tools/CMakeFiles/record_streaming.dir/build.make tools/CMakeFiles/record_streaming.dir/build
.PHONY : record_streaming/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f tools/CMakeFiles/server.dir/build.make tools/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named sine

# Build rule for target.
sine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sine
.PHONY : sine

# fast build rule for target.
sine/fast:
	$(MAKE) -f tools/CMakeFiles/sine.dir/build.make tools/CMakeFiles/sine.dir/build
.PHONY : sine/fast

#=============================================================================
# Target rules for targets named stereo

# Build rule for target.
stereo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stereo
.PHONY : stereo

# fast build rule for target.
stereo/fast:
	$(MAKE) -f tools/CMakeFiles/stereo.dir/build.make tools/CMakeFiles/stereo.dir/build
.PHONY : stereo/fast

#=============================================================================
# Target rules for targets named test_compound

# Build rule for target.
test_compound: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_compound
.PHONY : test_compound

# fast build rule for target.
test_compound/fast:
	$(MAKE) -f tools/CMakeFiles/test_compound.dir/build.make tools/CMakeFiles/test_compound.dir/build
.PHONY : test_compound/fast

#=============================================================================
# Target rules for targets named test_compound2

# Build rule for target.
test_compound2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_compound2
.PHONY : test_compound2

# fast build rule for target.
test_compound2/fast:
	$(MAKE) -f tools/CMakeFiles/test_compound2.dir/build.make tools/CMakeFiles/test_compound2.dir/build
.PHONY : test_compound2/fast

#=============================================================================
# Target rules for targets named test_core_midi

# Build rule for target.
test_core_midi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_core_midi
.PHONY : test_core_midi

# fast build rule for target.
test_core_midi/fast:
	$(MAKE) -f tools/CMakeFiles/test_core_midi.dir/build.make tools/CMakeFiles/test_core_midi.dir/build
.PHONY : test_core_midi/fast

#=============================================================================
# Target rules for targets named test_dls

# Build rule for target.
test_dls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dls
.PHONY : test_dls

# fast build rule for target.
test_dls/fast:
	$(MAKE) -f tools/CMakeFiles/test_dls.dir/build.make tools/CMakeFiles/test_dls.dir/build
.PHONY : test_dls/fast

#=============================================================================
# Target rules for targets named test_midi

# Build rule for target.
test_midi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_midi
.PHONY : test_midi

# fast build rule for target.
test_midi/fast:
	$(MAKE) -f tools/CMakeFiles/test_midi.dir/build.make tools/CMakeFiles/test_midi.dir/build
.PHONY : test_midi/fast

#=============================================================================
# Target rules for targets named test_midi_in

# Build rule for target.
test_midi_in: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_midi_in
.PHONY : test_midi_in

# fast build rule for target.
test_midi_in/fast:
	$(MAKE) -f tools/CMakeFiles/test_midi_in.dir/build.make tools/CMakeFiles/test_midi_in.dir/build
.PHONY : test_midi_in/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f tools/CMakeFiles/version.dir/build.make tools/CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named vst

# Build rule for target.
vst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vst
.PHONY : vst

# fast build rule for target.
vst/fast:
	$(MAKE) -f tools/CMakeFiles/vst.dir/build.make tools/CMakeFiles/vst.dir/build
.PHONY : vst/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... components_clean"
	@echo "... components_print"
	@echo "... components_resolve"
	@echo "... edit_cache"
	@echo "... format"
	@echo "... rebuild_cache"
	@echo "... runsc"
	@echo "... faudio_framework"
	@echo "... faudio_tests"
	@echo "... custom"
	@echo "... erik"
	@echo "... faudio"
	@echo "... impulses"
	@echo "... io_simple_filter"
	@echo "... level"
	@echo "... list_audio"
	@echo "... list_midi"
	@echo "... play"
	@echo "... plug_audio"
	@echo "... plug_midi"
	@echo "... record"
	@echo "... record_streaming"
	@echo "... server"
	@echo "... sine"
	@echo "... stereo"
	@echo "... test_compound"
	@echo "... test_compound2"
	@echo "... test_core_midi"
	@echo "... test_dls"
	@echo "... test_midi"
	@echo "... test_midi_in"
	@echo "... version"
	@echo "... vst"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

