(in-package :cl-user)
(defctype system-directory-file-path string)
(defcfun (system-directory-home "fae_system_directory_home") system-directory-file-path)
(defcfun (system-directory-current "fae_system_directory_current") system-directory-file-path)
(defcfun (system-directory-create "fae_system_directory_create") :void (a system-directory-file-path))
(defcfun (system-directory-remove "fae_system_directory_remove") :void (a system-directory-file-path))
(defcfun (system-directory-read-file "fae_system_directory_read_file") string (a system-directory-file-path))
(defcfun (system-directory-write-file "fae_system_directory_write_file") :void (a system-directory-file-path) (b string))
(defcfun (system-directory-append-file "fae_system_directory_append_file") :void (a system-directory-file-path) (b string))