(in-package :cl-user)
(defctype system-event-type :int)
(defcfun (system-event-mouse-move "fae_system_event_mouse_move") event)
(defcfun (system-event-mouse-drag "fae_system_event_mouse_drag") event)
(defcfun (system-event-mouse-up "fae_system_event_mouse_up") event)
(defcfun (system-event-mouse-down "fae_system_event_mouse_down") event)
(defcfun (system-event-key-up "fae_system_event_key_up") event)
(defcfun (system-event-key-down "fae_system_event_key_down") event)
(defcfun (system-event-select "fae_system_event_select") event (a list))
(defcfun (system-event-receive "fae_system_event_receive") message-sender (a list))
(defcfun (system-event-write-std "fae_system_event_write_std") event (a event))
(defcfun (system-event-send-std "fae_system_event_send_std") message-receiver)
(defcfun (system-event-write-log "fae_system_event_write_log") event (a event))
(defcfun (system-event-send-log "fae_system_event_send_log") message-receiver)