
/** 
    @addtogroup DoremirAtomic
    
    Cross-platform atomic variables. Submodules contains lock-free data structures.
 */
module Doremir.Atomic
{                   
    import Doremir;
    import Doremir.Std;
    
    type Atomic = opaque;
    type Updater = (Ptr -> Ptr)*;

    create  : () -> Atomic;
    copy    : Atomic -> Atomic;
    swap    : (Atomic, Atomic) -> Void;
    destroy : Atomic -> Void;

    exchange : (Atomic, Ptr, Ptr) -> Bool;
    get     : Atomic -> Ptr;
    set     : (Atomic, Ptr) -> Void;
    add     : (Atomic, Ptr) -> Void;
    modify  : (Atomic, Updater) -> Void;
}

