
/** 
    @addtogroup Doremir
    @addtogroup AudioEngine
    
    This is the top level module. Top import the audio engine, use
    
    ~~~~~~~~~~~~~~~~~~~~~{.c}
    #import <doremir/audio_engine.h>
    ~~~~~~~~~~~~~~~~~~~~~
    
 */
module Doremir.AudioEngine
{
    // import Doremir.Atomic;
    // import Doremir.Buffer;
    // import Doremir.List;
    // import Doremir.Map;
    // import Doremir.Midi;
    // import Doremir.Pair;
    // import Doremir.PriorityQueue;
    // import Doremir.Ratio;
    // import Doremir.Set;
    // import Doremir.String;    
    // import Doremir.Thread;
    // import Doremir.Thread.Future;
    // import Doremir.Thread.Improving;

    import Doremir.AudioEngine.Device.Audio;
    import Doremir.AudioEngine.Device.Midi;  
    // FIXME name collision
    // import Doremir.AudioEngine.Device.Buffer;
    import Doremir.AudioEngine.Device.File;
    import Doremir.AudioEngine.Processor;
    import Doremir.AudioEngine.Dispatcher;
    import Doremir.AudioEngine.Scheduler;
    import Doremir.AudioEngine.Time;    
}