
/** 
    @addtogroup Doremir
    @addtogroup AudioEngine
    
    This is the top level module. Top import the audio engine, use
    
    ~~~~~~~~~~~~~~~~~~~~~{.c}
    #import <doremir/audio_engine.h>
    ~~~~~~~~~~~~~~~~~~~~~
    
 */
module Doremir.AudioEngine
{
    import Doremir.Atomic;
    
    import Doremir.Buffer;
    import Doremir.List;
    import Doremir.Map;
    import Doremir.Midi;
    import Doremir.Pair;
    // FIXME not properly unmangled
    // import Doremir.PriorityQueue
    import Doremir.Ratio;
    import Doremir.Set;
    import Doremir.String;    
    import Doremir.Thread;
    import Doremir.Thread.Future;
    import Doremir.Thread.Improving;
    
}