
/** 
    @addtogroup DoremirAudioEngine
    
    This modules exports the entire audio engine. To import it, you can simply use:
    
    ~~~~~~~~~~~~~~~~~~~~~
    #import <doremir/audio_engine.h>
    ~~~~~~~~~~~~~~~~~~~~~
    
 */
module Doremir.AudioEngine
{
    import Doremir.Device.Audio;
    import Doremir.Device.Midi;  
    import Doremir.Device.File;
    import Doremir.Processor;
    import Doremir.Dispatcher;
    import Doremir.Scheduler;
    import Doremir.Time;    
}