
/** 
    @addtogroup DoremirBuffer
    
    Low-level buffer data structure. Each buffer is a mutable sequence of bytes with single-ownership
    semantics. The length of a buffer can never change, but its memory can be reused using the destructive
    resize operation.
    
    Note that buffers are not collections as their contents are mutable.


    @par Literals
    - `buffer(size)` 

    @par Implements 
    - doremir_copy_t
    - doremir_destroy_t
    - doremir_string_show_t

    @see 
    - [Data structures](@ref DataStructures)
 */
module Doremir.Buffer
{
    import Doremir;
    import Doremir.Std;
    import Doremir.Pair;
    import Doremir.String;
    import Doremir.Type;

    /** @typedef doremir_buffer_t
        The buffer. 
     */
    type Buffer = opaque;

    create  : (Size) -> Buffer;
    copy    : Buffer -> Buffer;
    resize  : (Size, Buffer) -> Buffer;
    destroy : Buffer -> Void;

    size    : Buffer -> Size;  
    get     : (Buffer, Size) -> UInt8;
    set     : (Buffer, Size, UInt8) -> Void;

    getInt16  : (Buffer, Size) -> Int16;
    getInt32  : (Buffer, Size) -> Int32;
    getInt64  : (Buffer, Size) -> Int64;
    getFloat  : (Buffer, Size) -> Float;
    getDouble : (Buffer, Size) -> Double;

    setInt16  : (Buffer, Size, Int16) -> Void;
    setInt32  : (Buffer, Size, Int32) -> Void;
    setInt64  : (Buffer, Size, Int64) -> Void;    
    setFloat  : (Buffer, Size, Float) -> Void;
    setDouble : (Buffer, Size, Double) -> Void;    

    readRaw : FilePath -> Buffer;
    writeRaw : (FilePath,Buffer) -> Void;
    
    readAudio : FilePath -> Pair; // (Type,Buffer)
    writeAudio : (FilePath,Type,Buffer) -> Void;

    unsafeAddress : Buffer -> Void*;
}