
/**
    @addtogroup DoremirDirectory
    
    Cross-platform directory utilities.    
 */

module Doremir.Directory
{
    import Doremir;
    import Doremir.String;

    home : () -> FilePath;
    current : () -> FilePath;
    create : FilePath -> Void;
    remove : FilePath -> Void;

    readFile : FilePath -> String;
    writeFile : (FilePath,String) -> Void;
    appendFile : (FilePath,String) -> Void;
}