
/**
    @addtogroup DoremirDevice
    
    Provides input and output devices.
    
 */

/**
    @addtogroup DoremirDispatcher
    
    Provides message dispatching.
    
 */
module Doremir.Dispatcher
{
    import Doremir;
    import Doremir.Std;
    import Doremir.List;

    type Message = List;
    type Address = Ptr;


    /** @interface doremir_dispatcher_sender_t */
    type Sender = struct {
        send : ((Ptr, Address, List) -> Void)*
    };

    /** @interface doremir_dispatcher_receiver_t */
    type Receiver = struct {
        receive : ((Ptr, Sender*) -> Void)*
    };

    /** @interface doremir_dispatcher_t */
    type Dispatcher = struct {
        send : ((Ptr, Address, List) -> Void)*,
        receive : ((Ptr, Sender*) -> Void)*
    };
}