
/**
    @addtogroup DoremirAudioEngineDevice
    
    Provides input and output devices.
    
 */

/**
    @addtogroup DoremirAudioEngineDispatcher
    
    Provides message dispatching.
    
 */
module Doremir.Dispatcher
{
    import Doremir.Std;
    import Doremir.List;

    type Message = List;

    /** @interface doremir_thread_dispatcher_t */
    type Dispatcher = struct {
        receive : (List -> Void)*,
        send : ((List -> Void)* -> Void)*
    };
}