
/**
    @addtogroup DoremirError
    
    Error handling types and functions.
 */                                             
 
 module Doremir.Error
{
    import Doremir;
    import Doremir.String;

    type Severity = enum {
        Info, Warning, Error, Misc
    };

    /** @interface doremir_error_t
        Error interface.
    */
    type Interface  = struct {
        severity : (Ptr -> Severity)*,
        message : (Ptr -> String)*,
        origin : (Ptr -> String)*
    };    
    type Error = opaque;
    
    createSimple : (Severity, String, String) -> Error;

    severity : Error -> Severity;
    message : Error -> String;
    origin : Error -> String;

    // coloured, err
    format : (Bool,Error) -> String;

    check : Ptr -> Bool;
    log : (Ptr,Error) -> Void; // Pass to global logger now

    // First param is context (ignored), second is error
    // log : (Ptr,Ptr) -> Void; // Pass to global logger now
}