
/** 
    @addtogroup DoremirGraph
    
    Immutable directed graph data structure.

    @par Literals

    @par Requires 
    - doremir_equal_t

    @par Implements 
    - doremir_equal_t
    - doremir_copy_t
    - doremir_destroy_t
    - doremir_dynamic_t
    - doremir_string_show_t

    @see 
    - @ref Collections
    
 */
module Doremir.Graph 
{
    import Doremir;
    import Doremir.Pair;
    import Doremir.List;
    import Doremir.String;
    
    type Graph = opaque;
    type Node = Ptr;
    type Edge = Ptr;
    type NodeList = List;
    type EdgeList = List;

    // Constructors
    empty            : () -> Graph;
    insert           : (Node,Graph) -> Graph;
    remove           : (Node,Graph) -> Graph;
    destroy          : Graph -> Void;

    // Edges
    connect          : (Edge,Node,Node,Graph) -> Graph;
    disconnect       : (Node,Node,Graph) -> Graph;

    // Introspection
    // nodes            : Graph -> NodeList;
    // edges            : Graph -> EdgeList;
    // head             : (Edge, Graph) -> Node;
    // tail             : (Edge, Graph) -> Node;
    // from             : (Node, Graph) -> EdgeList;
    // to               : (Node, Graph) -> EdgeList;
    // children         : (Node, Graph) -> NodeList;
    // parents          : (Node, Graph) -> NodeList;

    // Predicates
    // hasNode          : (Node, Graph) -> Bool;
    // hasEdge          : (Edge, Graph) -> Bool;
    // succOf           : (Node, Node, Graph) -> Bool;
    // predOf           : (Node, Node, Graph) -> Bool;
    // directSuccOf     : (Node, Node, Graph) -> Bool;
    // directPredOf     : (Node, Node, Graph) -> Bool;

    // Conversions   
    fromList         : Pair -> Graph;   // [(e,(n,n))]
    toList           : Graph -> List;   // [(e,(n,n))]
}