
/**
    Provides the map data structure. 
 */
module Doremir.Map 
{
    import Doremir.Pair;
    
    type Map = opaque;
    type Key = Intptr;
    type Value = Intptr;
    
    empty   : () -> Map;
    single  : (Key, Value) -> Map;
    append  : (Map, Map) -> Map;
    destroy : (Map) -> Void;
    copy    : (Map) -> Map;
    swap    : (Map, Map) -> Void;
    fromPair : (Pair) -> Map;

    key            : (Map, Key) -> Bool;
    elem           : (Map, Value) -> Bool;
    entry          : (Map, Pair) -> Bool;
    submapOf       : (Map, Map) -> Bool;
    properSubmapOf : (Map, Map) -> Bool;

    // TODO what about equality?    
                                
    add           : (Map, Key, Value) -> Map;
    remove        : (Map, Key, Value) -> Void;
    addDest       : (Map, Key, Value) -> Map;
    removeDest    : (Map, Key, Value) -> Void;
}