
/**
    @addtogroup DoremirMessage

    Provides message dispatching.

    @note 
        This module is fairly low-level, you typically want to use the the
        [Event](@ref DoremirEvent) wrappers @ref doremir_event_send and @ref
        doremir_event_receive instead.

    Message passing is the process of delivering a *message* to an *address*. Any
    ordered type can be used as an addreses, but typically it is an objet with fast
    equality comparison such as an integer. Message passing is captured by two 
    interfaces: [SenderInterface](@ref doremir_message_sender_t) which provides messages, and 
    [ReceiverInterface](@ref doremir_message_receiver_t) which accepts them. Note that the method
    names are contrary to the interfaces: you *send* to a *receiver* and *receive*
    from a *sender*.
    
    The *dispatcher* type provides message passing accross thread boundaries:
    it implements both [SenderInterface](@ref doremir_message_sender_t) and 
    [ReceiverInterface](@ref doremir_message_receiver_t).
    
    @par Dispatcher literals
    - `dispatcher()`
    - `lockfree_dispatcher()`
    
    @par Dispatcher implements
    - doremir_destroy_t
    - doremir_message_sender_t
    - doremir_message_receiver_t
    - doremir_string_show_t

    @see
    - [Data structures](@ref DataStructures)

    
 */
module Doremir.Message
{
    import Doremir;
    import Doremir.Std;
    import Doremir.Pair;
    import Doremir.List;

    type Address = Ptr; // Must implement Equal, Order
    type Message = Ptr;

    /** @interface doremir_message_sender_t
    */
    type SenderInterface = struct {
        sync : (Ptr -> Void)*,
        receive : ((Ptr,Address) -> List)* // [Message]
    };
    /** @interface doremir_message_receiver_t
    */
    type ReceiverInterface = struct {
        send : ((Ptr,Address,Message) -> Void)*
    };

    type Sender = opaque;
    type Receiver = opaque;


    type Dispatcher = opaque;

    createDispatcher : () -> Dispatcher;
    createLockfreeDispatcher : () -> Dispatcher;
    destroyDispatcher : Dispatcher -> Void;


    // Request message to be sent on address
    send : (Ptr,Address,Message) -> Void;

    // Fetch all new messages
    sync : Ptr -> Void;
    // Get fetched messages on addresses
    receive : (Ptr,Address) -> List; // [Message]


}