
/** 
    @addtogroup DoremirMidi
    
    Midi messages.

    @par Literals
    - `midi(note_on, 60, 127)`
    - `midi(note_off, 60, 127)`
    - `midi(0x9, 60, 127)`
    - `midi_sysex(buffer)`

    @par Implements 
    - doremir_equal_t
    - doremir_order_t
    - doremir_string_show_t
    - doremir_copy_t
    - doremir_destroy_t
    - doremir_dynamic_t
    
 */
module Doremir.Midi
{
    import Doremir.Std;
    import Doremir.Pair;
    import Doremir.Buffer;
    
    type Status = enum {
        NoteOff,
        NoteOn,
        AfterTouch,
        ControlChange,
        ProgramChange,
        ChannelPressure,
        PitchWheel,
        Sysex 
    };     

    type Channel = Int;    
    type Data    = Int;    
    type Midi    = opaque;

    createSimple : (Status, Int, Int) -> Midi;
    createSysex  : Buffer -> Midi;
    copy         : Midi -> Midi;
    destroy      : Midi -> Void;

    status  : Midi -> Status;
    channel : Midi -> Channel;

    isSimple      : Midi -> Bool;
    simpleData    : Midi -> Pair;
    isSysex       : Midi -> Bool;
    sysexData     : Midi -> Buffer;    
}