
/** 
    @addtogroup DoremirPair
    
    Pair data structure and some utility functions.

    @par Implements 
        doremir_equal_t
        doremir_order_t
        doremir_dynamic_t
        doremir_destroy_t
    @see 
        \ref Collections

 */
module Doremir.Pair
{
    import Doremir;
    import Doremir.Std;

    // FIXME needed by some allocation routines
    type Type = Size;

    type Unary = Ptr;
    type Pair = struct { fst : Ptr, snd : Ptr };
    
    map : (Unary, Pair) -> Pair;
}