
/** 
    @addtogroup DoremirPair
    
    Pair data structure.

    @par Literals
    - `pair(1, 2)`

    @par Implements 
    - doremir_equal_t
    - doremir_order_t
    - doremir_copy_t
    - doremir_destroy_t
    - doremir_dynamic_t
    - doremir_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Doremir.Pair
{
    import Doremir;
    import Doremir.List;

    type Pair = opaque;

    create  : (Ptr, Ptr) -> Pair;
    copy   : Pair -> Pair;
    destroy : Pair -> Void;

    fst : Pair -> Ptr;
    snd : Pair -> Ptr;

    dup : Ptr -> Pair;
    swap : Pair -> Pair;
    assoc : Pair -> Pair;    
    unassoc : Pair -> Pair;
    
    toList : Pair -> List;
}

