
/** 
    @addtogroup DoremirPair
    
    Pair data structure and some utility functions.

    \warning To store a primitive (non-pointer) value in a collection, the \ref WrapperFunctions must be used.

 */
module Doremir.Pair
{
    import Doremir;
    import Doremir.Std;

    // FIXME needed by some allocation routines
    type Type = Size;

    type Unary = Ptr;
    type Pair = struct { fst : Ptr, snd : Ptr };
    
    map : (Unary, Pair) -> Pair;
}