
/** 
    @addtogroup DoremirPlot
    
    Provides data plotting.
    
    @warning
        This modules is intended for internal testing and works only on OS X at the
        moment.
 */
module Doremir.Plot
{
    import Doremir;
    import Doremir.Std;

    /**
        @typedef doremir_plot_func_t
        
        Callback to be invoked by the plotter.
        
        @param context  Context reference.
        @param index    Plot index, from \f$0\f$ to \f$4\f$. 
        @param time     Time in seconds, starting at \f$0\f$. 
        @param x        Value of x, from \f$-1\f$ to \f$1\f$. 
     */
    type Func = ((Ptr, Int, Double, Double) -> Double)*;

    show : (Func, Ptr, Nullary, Ptr) -> Void;
}