
/** 
    @addtogroup DoremirPriorityQueue
    
    Priority queue data structure.
    
    @par Requires 
    - doremir_order_t
    @par Implements 
    - doremir_equal_t
    - doremir_string_show_t
    - doremir_destroy_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Doremir.PriorityQueue
{
    import Doremir;

    type PriorityQueue = opaque;
    
    empty  : () -> PriorityQueue;
    single : Ptr -> PriorityQueue;
    destroy : PriorityQueue -> Void;
    
    merge   : (PriorityQueue, PriorityQueue) -> Void;
    insert  : (Ptr, PriorityQueue) -> Void; // should arguably swap args
    peek    : PriorityQueue -> Ptr;
    pop     : PriorityQueue -> Ptr;
}