
/** 
    @addtogroup DoremirPriorityQueue
    
    Priority queue data structure.

 */
module Doremir.PriorityQueue
{
    import Doremir.Std;

    type PriorityQueue = opaque;
    type Value = Intptr;
    
    create  : () -> PriorityQueue;
    swap    : (PriorityQueue, PriorityQueue) -> Void;
    destroy : PriorityQueue -> Void;
    
    insert  : (PriorityQueue, Value) -> Void;
    peek    : PriorityQueue -> Value;
    pop     : PriorityQueue -> Value;
}