
/** 
    @addtogroup DoremirPriorityQueue
    
    Priority queue data structure.
    
    Note that priority queues are not collections as their contents are mutable.

    @par Requires 
    - doremir_order_t
    @par Implements 
    - doremir_equal_t
    @see 
    - @ref Collections

 */
module Doremir.PriorityQueue
{
    import Doremir;

    type PriorityQueue = opaque;
    
    create  : () -> PriorityQueue;
    swap    : (PriorityQueue, PriorityQueue) -> Void;
    destroy : PriorityQueue -> Void;
    
    insert  : (PriorityQueue, Ptr) -> Void;
    peek    : PriorityQueue -> Ptr;
    pop     : PriorityQueue -> Ptr;
}