
/**
    @addtogroup DoremirProcessor
    
    Provides signal processors.

    @par Literals
    - `par(p,q)`
    - `seq(p,q)`
    - `fst(p)`
    - `snd(p)`
    - `loop(p)`
    - `delay(n,T)`
    - `id(T)`
    - `const(T,v)`
    - `split(T)`

    @par Implements
    - TODO receiver?        
    - doremir_string_show_t
    - doremir_destroy_t
 */
module Doremir.Processor
{
    import Doremir;
    import Doremir.Time;
    import Doremir.Type;
    import Doremir.Buffer;
    import Doremir.Message;

    /** @struct doremir_processor_info_t 
        Information available to a processor at processing time. 
      */
    type Info = struct {
        sampleRate  : Double,
        numSamples  : Size,
        sampleTime  : Size,
        totalTime   : Time,
        dispatcher  : Dispatcher
    };     
    
    // infoDefault : Info* -> Void;  

    /** @typedef doremir_processor_samples_t
        The samples manipulated by a processor.
     */
    type Samples = Buffer;

    /** @interface doremir_processor_interface_t 
        Processing interface. */
    type Interface = struct {
        before  : ((Ptr, Info*) -> Void)*,
        process : ((Ptr, Info*, Samples) -> Void)*,
        after   : ((Ptr, Info*) -> Void)*,
        inputType : (Ptr -> Type)*,
        outputType : (Ptr -> Type)*
    };

    /** @typedef doremir_processor_any_t 
        A processor of unkown type.
     */
    type Processor = opaque;   
    
    unary   : (Type, Type, Unary) -> Processor;                   // a ~> b
    binary : (Type, Type, Type, Binary) -> Processor;             // (a,b) ~> c
    ternary : (Type, Type, Type, Type, Ternary) -> Processor;     // (a,b,c) ~> d
    
    identity : Type -> Processor;                 // a ~> a
    constant : (Type, Type, Ptr) -> Processor;    // a ~> b
    delay    : (Type, Size) -> Processor;         // a ~> a
    split    : Type -> Processor;                 // a ~> (a,a)

    seq      : (Processor, Processor) -> Processor;           // (a ~> b), (b ~> c) -> (a ~> c)
    par      : (Processor, Processor) -> Processor;           // (a ~> b), (c ~> d) -> (a,c ~> b,d)
    loop     : Processor -> Processor;                  // (a,c ~> b,d) -> (a ~> b)

    // first    : Processor -> Processor;                  // (a ~> b) -> (a,c ~> b,c)
    // second   : Processor -> Processor;                  // (a ~> b) -> (c,a ~> c,b)
    // fold     : Processor -> Processor;                  // (a,a ~> b) -> [a x n] ~> a ~> b
    // unfold   : Processor -> Processor;                  // (a ~> b,b) -> a ~> Int ~> [a x n]
    
    // cos         : Type -> Processor;
    // sin         : Type -> Processor;
    // tan         : Type -> Processor;
    // acos        : Type -> Processor;
    // asin        : Type -> Processor;
    // atan        : Type -> Processor;
    // 
    // add         : Type -> Processor;
    // subtract    : Type -> Processor;
    // multiply    : Type -> Processor;
    // divide      : Type -> Processor;
    // modulo      : Type -> Processor;
    // absolute    : Type -> Processor;
    // 
    // and         : Type -> Processor;
    // or          : Type -> Processor;
    // not         : Type -> Processor;
    // bitAnd      : Type -> Processor;
    // bitOr       : Type -> Processor;
    // bitNot      : Type -> Processor;
    // bitXor      : Type -> Processor;  
    
}