
/**
    @addtogroup DoremirProcessor
    
    Provides signal processors.
    
 */
module Doremir.Processor
{
    import Doremir.Std;
    import Doremir.Buffer;

    type Samples = Buffer;

    type Info = struct {
        sampleRate : Double,
        sampleCount : Long,
        realTime : Bool
    };

    /** @interface doremir_processor_t */
    type Processor = struct {
        before : (Info* -> Void)*,
        process : ((Info*, Samples) -> Samples)*,
        after : (Info* -> Void)*
    };
}