
/**
    @addtogroup DoremirProcessor
    
    Provides signal processors.
    
 */
module Doremir.Processor
{
    import Doremir;
    import Doremir.Buffer;

    type Samples = Buffer;

    type Info = struct {
        sampleRate : Double,
        sampleCount : Long,
        realTime : Bool
    };

    /** @interface doremir_processor_t */
    type Processor = struct {
        before  : ((Ptr, Info*) -> Void)*,
        process : ((Ptr, Info*, Samples) -> Samples)*,
        after   : ((Ptr, Info*) -> Void)*
    };
}