
/** 
    @addtogroup DoremirRatio
    
    Fixed-precision rational numbers.

 */
module Doremir.Ratio 
{
    import Doremir.Std;

    type Nom    = Int32;
    type Denom  = Int32;
    type Ratio  = opaque;

    create  : (Nom, Denom) -> Ratio;
    nom     : Ratio -> Nom;
    denom   : Ratio -> Denom;
    destroy : Ratio -> Void;
            
    add : (Ratio, Ratio) -> Ratio;
    subtract : (Ratio, Ratio) -> Ratio;
    multiply : (Ratio, Ratio) -> Ratio;
    divide : (Ratio, Ratio) -> Ratio;
    remainder : (Ratio, Ratio) -> Ratio;
    succ : Ratio -> Ratio;
    pred : Ratio -> Ratio;
    negate : Ratio -> Ratio;
    recip : Ratio -> Ratio;
}