
/**
    @addtogroup DoremirScheduler
    
    Provides task scheduling.

    @par Implements 
    - doremir_equal_t
    - doremir_string_show_t
    - doremir_destroy_t
    
 */
module Doremir.Scheduler
{
    import Doremir;
    import Doremir.Time;
    import Doremir.Event;

    type Action = Nullary;
    type Scheduler = opaque;
    

    create  : (Ptr) -> Scheduler; // Requires Clock
    destroy : Scheduler -> Void;
    
    schedule : (Scheduler, Event) -> Void;
    execute  : Scheduler -> Void;
    // Loop until finished
    run      : Scheduler -> Void;
}