
/**
    @addtogroup DoremirScheduler
    
    Provides task scheduling.
    
 */
module Doremir.Scheduler
{
    import Doremir;
    import Doremir.Thread.Improving;

    type Time = Int; // TODO
    type Action = Nullary;
    
    type Scheduler = opaque;

    create  : Improving -> Scheduler;
    // swap    : (Scheduler, Scheduler) -> Void;
    destroy : Scheduler -> Void;
    
    schedule : (Scheduler, Time, Action) -> Void;
    execute  : Scheduler -> Void;
}