
/** 
    @addtogroup DoremirSet
    
    Immutable ordered set data structure.

    @par Requires 
        doremir_order_t
    @par Implements 
        doremir_equal_t
        doremir_copy_t
        doremir_destroy_t
        doremir_dynamic_t
        doremir_string_show_t
    @see 
        \ref Collections
    
 */
module Doremir.Set
{
    import Doremir;
    import Doremir.String;

    type Set = opaque;
    
    empty            : () -> Set;
    add              : (Ptr, Set) -> Set;
    remove           : (Ptr, Set) -> Void;
    copy             : Set -> Set;
    destroy          : Set -> Void;

    has              : (Ptr, Set) -> Bool;
    size             : Set -> Int;

    isEmpty          : Set -> Bool;
    isSingle         : Set -> Bool;
    isSubsetOf       : (Set, Set) -> Bool;
    isProperSubsetOf : (Set, Set) -> Bool;

    sum              : (Set, Set) -> Set;
    product          : (Set, Set) -> Set;
    difference       : (Set, Set) -> Set;
    cartesian        : (Set, Set) -> Set;
    power            : Set -> Set;

    equal       : (Set, Set) -> Bool;
    lessThan    : (Set, Set) -> Bool;
    greaterThan : (Set, Set) -> Bool;
    show        : Set -> String;

}