
/** 
    @addtogroup DoremirSet
    
    Immutable ordered set data structure.

    @par Requires 
    - doremir_order_t
    @par Implements 
    - doremir_equal_t
    - doremir_string_show_t
    - doremir_copy_t
    - doremir_destroy_t
    - doremir_dynamic_t
    @see 
    - @ref Collections
    
 */
module Doremir.Set
{
    import Doremir;
    import Doremir.String;

    type Set = opaque;
    
    // Constructors
    empty            : () -> Set;
    single           : Ptr -> Set;
    add              : (Ptr, Set) -> Set;
    remove           : (Ptr, Set) -> Set;
    copy             : Set -> Set;
    destroy          : Set -> Void;    

    // Size
    size             : Set -> Int;
    isEmpty          : Set -> Bool;
    isSingle         : Set -> Bool;

    // Predicates
    has              : (Ptr, Set) -> Bool;
    isSubsetOf       : (Set, Set) -> Bool;
    isProperSubsetOf : (Set, Set) -> Bool;

    // Set operations
    sum              : (Set, Set) -> Set;
    product          : (Set, Set) -> Set;
    difference       : (Set, Set) -> Set;
    cartesian        : (Set, Set) -> Set;
    power            : Set -> Set;
}

