
/** 
    @addtogroup DoremirString
    
    String operations.

 */
module Doremir.String
{
    import Doremir;

    type String = opaque;
    type FilePath = String;

    // toUtf8  : String -> Utf8;
    // toUtf16 : String -> Utf16;
    // toUtf32 : String -> Utf32;
    // fromUtf8  : Utf8 -> String;
    // fromUtf16 : Utf16 -> String;
    // fromUtf32 : Utf32 -> String;
    
    empty : () -> String;
    single : Char -> String;
    length : String -> Int;

    /** @interface doremir_string_show_t 
        Printable objects.
    */
    type Show  = struct {
        show : (Ptr -> String)*
    };

}