(in-package :doremir)
(defctype atomic :pointer)
(defctype atomic-updater (:pointer (:pointer :void)))
(defcfun (atomic-create "doremir_atomic_create") atomic)
(defcfun (atomic-copy "doremir_atomic_copy") atomic (a atomic))
(defcfun (atomic-swap "doremir_atomic_swap") :void (a atomic) (b atomic))
(defcfun (atomic-destroy "doremir_atomic_destroy") :void (a atomic))
(defcfun (atomic-exchange "doremir_atomic_exchange") :boolean (a atomic) (b ptr) (c ptr))
(defcfun (atomic-get "doremir_atomic_get") ptr (a atomic))
(defcfun (atomic-set "doremir_atomic_set") :void (a atomic) (b ptr))
(defcfun (atomic-add "doremir_atomic_add") :void (a atomic) (b ptr))
(defcfun (atomic-modify "doremir_atomic_modify") :void (a atomic) (b atomic-updater))