(in-package :audio-engine)
(defcfun (audioengine-initialize "doremir_audio_engine_initialize") :void)
(defcfun (audioengine-terminate "doremir_audio_engine_terminate") :void)
(defctype audioengine-log-func (:pointer (:pointer :void)))
(defcfun (audioengine-set-log-file "doremir_audio_engine_set_log_file") :void (a string-file-path))
(defcfun (audioengine-set-log-std "doremir_audio_engine_set_log_std") :void)
(defcfun (audioengine-set-log "doremir_audio_engine_set_log") :void (a audioengine-log-func) (b ptr))
(defcfun (audioengine-log "doremir_audio_engine_log") :void (a ptr) (b error))
(defcfun (audioengine-log-info "doremir_audio_engine_log_info") :void (a string))
(defcfun (audioengine-log-warning "doremir_audio_engine_log_warning") :void (a string))
(defcfun (audioengine-log-error "doremir_audio_engine_log_error") :void (a string))
(defcfun (audioengine-log-info-from "doremir_audio_engine_log_info_from") :void (a string) (b string))
(defcfun (audioengine-log-warning-from "doremir_audio_engine_log_warning_from") :void (a string) (b string))
(defcfun (audioengine-log-error-from "doremir_audio_engine_log_error_from") :void (a string) (b string))