(in-package :audio-engine)
(define-foreign-type buffer-type () () (:actual-type :pointer))
(define-parse-method buffer () (make-instance 'buffer-type))
(defclass buffer () ((buffer-ptr :initarg :buffer-ptr)))
(defmethod translate-to-foreign (x (type buffer-type)) (slot-value x 'buffer-ptr))
(defmethod translate-from-foreign (x (type buffer-type)) (make-instance 'buffer :buffer-ptr x))
(defcfun (buffer-create "doremir_buffer_create") buffer (a :int32))
(defcfun (buffer-copy "doremir_buffer_copy") buffer (a buffer))
(defcfun (buffer-resize "doremir_buffer_resize") buffer (a :int32) (b buffer))
(defcfun (buffer-destroy "doremir_buffer_destroy") :void (a buffer))
(defcfun (buffer-size "doremir_buffer_size") :int32 (a buffer))
(defcfun (buffer-peek "doremir_buffer_peek") :uint8 (a buffer) (b :int32))
(defcfun (buffer-poke "doremir_buffer_poke") :void (a buffer) (b :int32) (c :uint8))
(defcfun (buffer-peek-int16 "doremir_buffer_peek_int16") :int16 (a buffer) (b :int32))
(defcfun (buffer-peek-int32 "doremir_buffer_peek_int32") :int32 (a buffer) (b :int32))
(defcfun (buffer-peek-int64 "doremir_buffer_peek_int64") :int64 (a buffer) (b :int32))
(defcfun (buffer-peek-float "doremir_buffer_peek_float") :float (a buffer) (b :int32))
(defcfun (buffer-peek-double "doremir_buffer_peek_double") :double (a buffer) (b :int32))
(defcfun (buffer-poke-int16 "doremir_buffer_poke_int16") :void (a buffer) (b :int32) (c :int16))
(defcfun (buffer-poke-int32 "doremir_buffer_poke_int32") :void (a buffer) (b :int32) (c :int32))
(defcfun (buffer-poke-int64 "doremir_buffer_poke_int64") :void (a buffer) (b :int32) (c :int64))
(defcfun (buffer-poke-float "doremir_buffer_poke_float") :void (a buffer) (b :int32) (c :float))
(defcfun (buffer-poke-double "doremir_buffer_poke_double") :void (a buffer) (b :int32) (c :double))
(defcfun (buffer-read-raw "doremir_buffer_read_raw") buffer (a string-file-path))
(defcfun (buffer-write-raw "doremir_buffer_write_raw") :void (a string-file-path) (b buffer))
(defcfun (buffer-read-audio "doremir_buffer_read_audio") pair (a string-file-path))
(defcfun (buffer-write-audio "doremir_buffer_write_audio") :void (a string-file-path) (b type) (c buffer))
(defcfun (buffer-unsafe-address "doremir_buffer_unsafe_address") (:pointer :void) (a buffer))