(in-package :audio-engine)
(defctype error-category :int)
(defctype error (:pointer :void))
(defcfun (error-severity "doremir_error_severity") error-category (a ptr))
(defcfun (error-message "doremir_error_message") string (a ptr))
(defcfun (error-origin "doremir_error_origin") string (a ptr))
(defcfun (error-check "doremir_error_check") :boolean (a ptr))
(defcfun (error-log "doremir_error_log") :void (a ptr) (b ptr))