(in-package :audio-engine)
(define-foreign-type event-type () () (:actual-type :pointer))
(define-parse-method event () (make-instance 'event-type))
(defclass event () ((event-ptr :initarg :event-ptr)))
(defmethod translate-to-foreign (x (type event-type)) (slot-value x 'event-ptr))
(defmethod translate-from-foreign (x (type event-type)) (make-instance 'event :event-ptr x))
(defcfun (event-never "doremir_event_never") event)
(defcfun (event-now "doremir_event_now") event (a ptr))
(defcfun (event-delay "doremir_event_delay") event (a time) (b event))
(defcfun (event-merge "doremir_event_merge") event (a event) (b event))
(defcfun (event-switch "doremir_event_switch") event (a event) (b event) (c event))
(defcfun (event-receive "doremir_event_receive") event (a message-sender) (b message-address))
(defcfun (event-send "doremir_event_send") event (a message-receiver) (b message-address) (c event))
(defcfun (event-destroy "doremir_event_destroy") :void (a event))
(defcfun (event-first "doremir_event_first") event (a event))
(defcfun (event-rest "doremir_event_rest") event (a event))
(defcfun (event-later "doremir_event_later") event (a time) (b ptr))
(defcfun (event-repeat "doremir_event_repeat") event (a time) (b ptr))
(defcfun (event-after "doremir_event_after") event (a event) (b event))
(defcfun (event-before "doremir_event_before") event (a event) (b event))
(defcfun (event-sample "doremir_event_sample") event (a event) (b event))
(defcfun (event-toggle "doremir_event_toggle") event (a event) (b event))
(defcfun (event-filter "doremir_event_filter") event (a pred) (b ptr) (c event))
(defcfun (event-dfilter "doremir_event_dfilter") event (a pred) (b ptr) (c event))
(defcfun (event-map "doremir_event_map") event (a unary) (b ptr) (c event))
(defcfun (event-dmap "doremir_event_dmap") event (a unary) (b ptr) (c event))
(defcfun (event-map2 "doremir_event_map2") event (a binary) (b ptr) (c event) (d event))
(defcfun (event-dmap2 "doremir_event_dmap2") event (a binary) (b ptr) (c event) (d event))
(defcfun (event-offset "doremir_event_offset") time (a event))
(defcfun (event-add-sync "doremir_event_add_sync") :void (a (:pointer (:pointer :void))) (b ptr) (c event))
(defcfun (event-values "doremir_event_values") list (a time) (b time) (c event))
(defcfun (event-has-values "doremir_event_has_values") :boolean (a time) (b time) (c event))
(defcfun (event-has-more "doremir_event_has_more") :boolean (a time) (b event))