(in-package :audio-engine)
(define-foreign-type event-type () () (:actual-type :pointer))
(define-parse-method event () (make-instance 'event-type))
(defclass event () ((event-ptr :initarg :event-ptr)))
(defmethod translate-to-foreign (x (type event-type)) (slot-value x 'event-ptr))
(defmethod translate-from-foreign (x (type event-type)) (make-instance 'event :event-ptr x))
(defcfun (event-never "doremir_event_never") event)
(defcfun (event-now "doremir_event_now") event (a ptr))
(defcfun (event-delay "doremir_event_delay") event (a time) (b event))
(defcfun (event-head "doremir_event_head") event (a event))
(defcfun (event-tail "doremir_event_tail") event (a event))
(defcfun (event-merge "doremir_event_merge") event (a event) (b event))
(defcfun (event-switch "doremir_event_switch") event (a event) (b event) (c event))
(defcfun (event-destroy "doremir_event_destroy") :void (a event))
(defcfun (event-external "doremir_event_external") event)
(defcfun (event-send "doremir_event_send") :void (a ptr) (b event))
(defcfun (event-offset "doremir_event_offset") time (a event))
(defcfun (event-has-value "doremir_event_has_value") :boolean (a event) (b time))
(defcfun (event-value "doremir_event_value") ptr (a event))