(in-package :audio-engine)
(define-foreign-type map-type () () (:actual-type :pointer))
(define-parse-method map () (make-instance 'map-type))
(defclass map () ((map-ptr :initarg :map-ptr)))
(defmethod translate-to-foreign (x (type map-type)) (slot-value x 'map-ptr))
(defmethod translate-from-foreign (x (type map-type)) (make-instance 'map :map-ptr x))
(defctype map-key ptr)
(defcfun (map-empty "doremir_map_empty") map)
(defcfun (map-copy "doremir_map_copy") map (a map))
(defcfun (map-destroy "doremir_map_destroy") :void (a map))
(defcfun (map-size "doremir_map_size") :int (a map))
(defcfun (map-is-empty "doremir_map_is_empty") :boolean (a map))
(defcfun (map-is-single "doremir_map_is_single") :boolean (a map))
(defcfun (map-add "doremir_map_add") map (a map-key) (b ptr) (c map))
(defcfun (map-set "doremir_map_set") map (a map-key) (b ptr) (c map))
(defcfun (map-remove "doremir_map_remove") map (a map-key) (b map))
(defcfun (map-dadd "doremir_map_dadd") map (a map-key) (b ptr) (c map))
(defcfun (map-dset "doremir_map_dset") map (a map-key) (b ptr) (c map))
(defcfun (map-dremove "doremir_map_dremove") map (a map-key) (b map))
(defcfun (map-add-entry "doremir_map_add_entry") map (a pair) (b map))
(defcfun (map-set-entry "doremir_map_set_entry") map (a pair) (b map))
(defcfun (map-remove-entry "doremir_map_remove_entry") map (a pair) (b map))
(defcfun (map-get "doremir_map_get") ptr (a map-key) (b map))
(defcfun (map-has-key "doremir_map_has_key") :boolean (a map-key) (b map))
(defcfun (map-has-elem "doremir_map_has_elem") :boolean (a ptr) (b map))
(defcfun (map-has-entry "doremir_map_has_entry") :boolean (a pair) (b map))
(defcfun (map-is-submap-of "doremir_map_is_submap_of") :boolean (a map) (b map))
(defcfun (map-is-proper-submap-of "doremir_map_is_proper_submap_of") :boolean (a map) (b map))
(defcfun (map-sum "doremir_map_sum") map (a map) (b map))
(defcfun (map-product "doremir_map_product") map (a map) (b map))
(defcfun (map-difference "doremir_map_difference") map (a map) (b map))
(defcfun (map-power "doremir_map_power") map (a map))
(defcfun (map-from-pair "doremir_map_from_pair") map (a pair))
(defcfun (map-from-list "doremir_map_from_list") map (a list))
(defcfun (map-to-list "doremir_map_to_list") list (a map))