(in-package :audio-engine)
(defctype message-address ptr)
(defctype message ptr)
(defctype message-sender-interface (:pointer :void))
(defctype message-receiver-interface (:pointer :void))
(define-foreign-type message-sender-type () () (:actual-type :pointer))
(define-parse-method message-sender () (make-instance 'message-sender-type))
(defclass message-sender () ((message-sender-ptr :initarg :message-sender-ptr)))
(defmethod translate-to-foreign (x (type message-sender-type)) (slot-value x 'message-sender-ptr))
(defmethod translate-from-foreign (x (type message-sender-type)) (make-instance 'message-sender :message-sender-ptr x))
(define-foreign-type message-receiver-type () () (:actual-type :pointer))
(define-parse-method message-receiver () (make-instance 'message-receiver-type))
(defclass message-receiver () ((message-receiver-ptr :initarg :message-receiver-ptr)))
(defmethod translate-to-foreign (x (type message-receiver-type)) (slot-value x 'message-receiver-ptr))
(defmethod translate-from-foreign (x (type message-receiver-type)) (make-instance 'message-receiver :message-receiver-ptr x))
(define-foreign-type message-dispatcher-type () () (:actual-type :pointer))
(define-parse-method message-dispatcher () (make-instance 'message-dispatcher-type))
(defclass message-dispatcher () ((message-dispatcher-ptr :initarg :message-dispatcher-ptr)))
(defmethod translate-to-foreign (x (type message-dispatcher-type)) (slot-value x 'message-dispatcher-ptr))
(defmethod translate-from-foreign (x (type message-dispatcher-type)) (make-instance 'message-dispatcher :message-dispatcher-ptr x))
(defcfun (message-create-dispatcher "doremir_message_create_dispatcher") message-dispatcher)
(defcfun (message-create-lockfree-dispatcher "doremir_message_create_lockfree_dispatcher") message-dispatcher)
(defcfun (message-destroy-dispatcher "doremir_message_destroy_dispatcher") :void (a message-dispatcher))
(defcfun (message-send "doremir_message_send") :void (a ptr) (b message-address) (c message))
(defcfun (message-sync "doremir_message_sync") :void (a ptr))
(defcfun (message-receive "doremir_message_receive") list (a ptr) (b message-address))