(in-package :doremir)
(defctype scheduler-action nullary)
(define-foreign-type scheduler-type () () (:actual-type :pointer))
(define-parse-method scheduler () (make-instance 'scheduler-type))
(defclass scheduler () ((scheduler-ptr :initarg :scheduler-ptr)))
(defmethod translate-to-foreign (x (type scheduler-type)) (slot-value x 'scheduler-ptr))
(defmethod translate-from-foreign (x (type scheduler-type)) (make-instance 'scheduler :scheduler-ptr x))
(defcfun (scheduler-create "doremir_scheduler_create") scheduler (a thread-improving))
(defcfun (scheduler-destroy "doremir_scheduler_destroy") :void (a scheduler))
(defcfun (scheduler-schedule "doremir_scheduler_schedule") :void (a scheduler) (b time) (c scheduler-action) (d ptr))
(defcfun (scheduler-execute "doremir_scheduler_execute") :void (a scheduler))