(in-package :doremir)
(defctype scheduler-action nullary)
(defctype scheduler :pointer)
(defcfun (scheduler-create "doremir_scheduler_create") scheduler (a thread-improving))
(defcfun (scheduler-destroy "doremir_scheduler_destroy") :void (a scheduler))
(defcfun (scheduler-schedule "doremir_scheduler_schedule") :void (a scheduler) (b time) (c scheduler-action) (d ptr))
(defcfun (scheduler-execute "doremir_scheduler_execute") :void (a scheduler))