(in-package :audio-engine)
(define-foreign-type signal-type () () (:actual-type :pointer))
(define-parse-method signal () (make-instance 'signal-type))
(defclass signal () ((signal-ptr :initarg :signal-ptr)))
(defmethod translate-to-foreign (x (type signal-type)) (slot-value x 'signal-ptr))
(defmethod translate-from-foreign (x (type signal-type)) (make-instance 'signal :signal-ptr x))
(defcfun (signal-type-of "doremir_signal_type_of") type (a signal))
(defcfun (signal-lift "doremir_signal_lift") signal (a unary) (b ptr) (c signal))
(defcfun (signal-lift2 "doremir_signal_lift2") signal (a binary) (b ptr) (c signal) (d signal))
(defcfun (signal-lift3 "doremir_signal_lift3") signal (a ternary) (b ptr) (c signal) (d signal) (e signal))
(defcfun (signal-apply "doremir_signal_apply") signal (a processor) (b signal))
(defcfun (signal-apply2 "doremir_signal_apply2") signal (a processor) (b signal) (c signal))
(defcfun (signal-apply3 "doremir_signal_apply3") signal (a processor) (b signal) (c signal) (d signal))
(defcfun (signal-constant "doremir_signal_constant") signal (a ptr))
(defcfun (signal-value "doremir_signal_value") signal (a event))
(defcfun (signal-delay "doremir_signal_delay") signal (a time) (b signal))
(defcfun (signal-add "doremir_signal_add") signal (a signal) (b signal))
(defcfun (signal-subtract "doremir_signal_subtract") signal (a signal) (b signal))
(defcfun (signal-multiply "doremir_signal_multiply") signal (a signal) (b signal))
(defcfun (signal-power "doremir_signal_power") signal (a signal) (b signal))
(defcfun (signal-divide "doremir_signal_divide") signal (a signal) (b signal))
(defcfun (signal-modulo "doremir_signal_modulo") signal (a signal) (b signal))
(defcfun (signal-absolute "doremir_signal_absolute") signal (a signal))
(defcfun (signal-not "doremir_signal_not") signal (a signal))
(defcfun (signal-and "doremir_signal_and") signal (a signal) (b signal))
(defcfun (signal-or "doremir_signal_or") signal (a signal) (b signal))
(defcfun (signal-xor "doremir_signal_xor") signal (a signal) (b signal))
(defcfun (signal-bit-not "doremir_signal_bit_not") signal (a signal) (b signal))
(defcfun (signal-bit-and "doremir_signal_bit_and") signal (a signal) (b signal))
(defcfun (signal-bit-or "doremir_signal_bit_or") signal (a signal) (b signal))
(defcfun (signal-bit-xor "doremir_signal_bit_xor") signal (a signal) (b signal))
(defcfun (signal-shift-left "doremir_signal_shift_left") signal (a signal) (b signal))
(defcfun (signal-shift-right "doremir_signal_shift_right") signal (a signal) (b signal))
(defcfun (signal-equal "doremir_signal_equal") signal (a signal) (b signal))
(defcfun (signal-less-than "doremir_signal_less_than") signal (a signal) (b signal))
(defcfun (signal-greater-than "doremir_signal_greater_than") signal (a signal) (b signal))
(defcfun (signal-less-than-equal "doremir_signal_less_than_equal") signal (a signal) (b signal))
(defcfun (signal-greater-than-equal "doremir_signal_greater_than_equal") signal (a signal) (b signal))
(defcfun (signal-acos "doremir_signal_acos") signal (a signal))
(defcfun (signal-asin "doremir_signal_asin") signal (a signal))
(defcfun (signal-atan "doremir_signal_atan") signal (a signal))
(defcfun (signal-cos "doremir_signal_cos") signal (a signal))
(defcfun (signal-sin "doremir_signal_sin") signal (a signal))
(defcfun (signal-tan "doremir_signal_tan") signal (a signal))
(defcfun (signal-exp "doremir_signal_exp") signal (a signal))
(defcfun (signal-log "doremir_signal_log") signal (a signal))
(defcfun (signal-log10 "doremir_signal_log10") signal (a signal))
(defcfun (signal-pow "doremir_signal_pow") signal (a signal))
(defcfun (signal-sqrt "doremir_signal_sqrt") signal (a signal))
(defcfun (signal-abs "doremir_signal_abs") signal (a signal))
(defcfun (signal-min "doremir_signal_min") signal (a signal))
(defcfun (signal-max "doremir_signal_max") signal (a signal))
(defcfun (signal-fmod "doremir_signal_fmod") signal (a signal))
(defcfun (signal-remainder "doremir_signal_remainder") signal (a signal))
(defcfun (signal-floor "doremir_signal_floor") signal (a signal))
(defcfun (signal-ceil "doremir_signal_ceil") signal (a signal))
(defcfun (signal-rint "doremir_signal_rint") signal (a signal))