(in-package :doremir)
(define-foreign-type time-type () () (:actual-type :pointer))
(define-parse-method time () (make-instance 'time-type))
(defclass time () ((time-ptr :initarg :time-ptr)))
(defmethod translate-to-foreign (x (type time-type)) (slot-value x 'time-ptr))
(defmethod translate-from-foreign (x (type time-type)) (make-instance 'time :time-ptr x))
(defcfun (time-create "doremir_time_create") time (a :int32) (b :int32) (c :int32) (d ratio))
(defcfun (time-copy "doremir_time_copy") time (a time))
(defcfun (time-destroy "doremir_time_destroy") :void (a time))
(defcfun (time-days "doremir_time_days") :int32 (a time))
(defcfun (time-hours "doremir_time_hours") :int32 (a time))
(defcfun (time-minutes "doremir_time_minutes") :int32 (a time))
(defcfun (time-seconds "doremir_time_seconds") :int32 (a time))
(defcfun (time-divisions "doremir_time_divisions") ratio (a time))
(defcfun (time-to-iso "doremir_time_to_iso") string (a time))