(in-package :faudio)
(define-foreign-type atomic-queue-type () () (:actual-type :pointer))
(define-parse-method atomic-queue () (make-instance 'atomic-queue-type))
(defclass atomic-queue () ((atomic-queue-ptr :initarg :atomic-queue-ptr)))
(defmethod translate-to-foreign (x (type atomic-queue-type)) (slot-value x 'atomic-queue-ptr))
(defmethod translate-from-foreign (x (type atomic-queue-type)) (make-instance 'atomic-queue :atomic-queue-ptr x))
(defcfun (atomic-queue-create "fa_atomic_queue_create") atomic-queue)
(defcfun (atomic-queue-destroy "fa_atomic_queue_destroy") :void (a atomic-queue))
(defcfun (atomic-queue-read "fa_atomic_queue_read") ptr (a atomic-queue))
(defcfun (atomic-queue-write "fa_atomic_queue_write") :boolean (a atomic-queue) (b ptr))

