(in-package :faudio)
(define-foreign-type atomic-ring-buffer-type () () (:actual-type :pointer))
(define-parse-method atomic-ring-buffer () (make-instance 'atomic-ring-buffer-type))
(defclass atomic-ring-buffer () ((atomic-ring-buffer-ptr :initarg :atomic-ring-buffer-ptr)))
(defmethod translate-to-foreign (x (type atomic-ring-buffer-type)) (slot-value x 'atomic-ring-buffer-ptr))
(defmethod translate-from-foreign (x (type atomic-ring-buffer-type)) (make-instance 'atomic-ring-buffer :atomic-ring-buffer-ptr x))
(defcfun (atomic-ringbuffer-create "fa_atomic_ring_buffer_create") atomic-ring-buffer (a :int32))
(defcfun (atomic-ringbuffer-copy "fa_atomic_ring_buffer_copy") atomic-ring-buffer (a atomic-ring-buffer))
(defcfun (atomic-ringbuffer-resize "fa_atomic_ring_buffer_resize") atomic-ring-buffer (a :int32) (b atomic-ring-buffer))
(defcfun (atomic-ringbuffer-swap "fa_atomic_ring_buffer_swap") :void (a atomic-ring-buffer) (b atomic-ring-buffer))
(defcfun (atomic-ringbuffer-destroy "fa_atomic_ring_buffer_destroy") :void (a atomic-ring-buffer))
(defcfun (atomic-ringbuffer-size "fa_atomic_ring_buffer_size") :int32 (a atomic-ring-buffer))
(defcfun (atomic-ringbuffer-read "fa_atomic_ring_buffer_read") :uint8 (a atomic-ring-buffer))
(defcfun (atomic-ringbuffer-write "fa_atomic_ring_buffer_write") :boolean (a atomic-ring-buffer) (b :uint8))

