
/**
    @addtogroup FaeAtomic

    Mutable atomic references.

    @par Literals
    - `atomic()`

    @par Implements
    - fae_equal_t
    - fae_order_t
    - fae_copy_t
    - fae_destroy_t
    - fae_string_show_t

    @see
    - [Data structures](@ref DataStructures)
 */
module Fae.Atomic
{
    import Fae;
    import Fae.Std;

    type Atomic = opaque;

    create  : () -> Atomic;
    copy    : Atomic -> Atomic;
    swap    : (Atomic, Atomic) -> Void;
    destroy : Atomic -> Void;

    exchange : (Atomic, Ptr, Ptr) -> Bool;
    get     : Atomic -> Ptr;
    set     : (Atomic, Ptr) -> Void;
    modify  : (Atomic, Unary, Ptr) -> Void;

    // TODO increment : (Atomic, Int32) -> Void;
}

