
/**
    @addtogroup FaeAudio

    Real-time audio devices. These device run processors on the input and output
    the underlying system, typically physical audio interfaces. A running audio
    computation is represented by a *stream*. Access to the current device setups
    is provided by *sessions*.

    @par Sessions implement
    - fae_equal_t
    - fae_destroy_t
    - fae_string_show_t

    @par Devices implement
    - fae_equal_t
    - fae_string_show_t

    Devices implement [Equal](@ref fae_equal_t) and [Show](@ref fae_string_show_t),
    but now destroy, as they are always managed by the underlying session.

    @par Streams implement
    - fae_time_clock_t
    - fae_message_sender_t
    - fae_message_receiver_t
    - fae_destroy_t
    - fae_string_show_t

    Stream implements [Clock](@ref fae_time_clock_t) by counting the number
    of processed samples. Precision is usually limited to the current frame size.

    Stream also implements [SenderInterface](@ref fae_message_sender_t) and
    [ReceiverInterface](@ref fae_message_sender_t), dispatching messages to the underlying
    processor network. The address of a processor can be obtained by @ref fae_processor_address.


    @see
    - @ref Devices
 */
module Fae.Audio
{
    import Fae.List;
    import Fae.Pair;
    import Fae.Device;
    import Fae.Error;
    import Fae.Type;

    type Session = opaque;
    type Device  = opaque;
    type Stream  = opaque;
    type SessionCallback = ((Ptr, Session) -> Session)*;
    type StreamCallback = ((Ptr, Stream) -> Stream)*;
    type StatusCallback = Nullary;

    beginSession : () -> Session;
    endSession : Session -> Void;
    withSession : (
        SessionCallback, Ptr,
        Callback, Ptr) -> Void;

    all : Session -> List;      // [Device]
    default : Session -> Pair;  // (Device,Device)
    defaultInput : Session -> Device;
    defaultOutput : Session -> Device;
    setStatusCallback : (StatusCallback, Ptr, Session) -> Void;

    name : Device -> String;
    hostName : Device -> String;
    hasInput : Device -> Bool;
    hasOutput : Device -> Bool;
    inputType : Device -> Type;
    outputType : Device -> Type;

    openStream : (Device, Ptr, Device) -> Stream;
    closeStream : Stream -> Void;
    withStream : (
        Device, Ptr, Device,
        StreamCallback, Ptr,
        Callback, Ptr
        ) -> Void;

}

