
/**
    @addtogroup FaeFae

    This modules exports Fae. Example usage:

    ~~~~
    #import <fae/fae.h>

    int main (int argc, char const *argv[])
    {
        fae_fae_initialize();

        ...

        fae_fae_terminate();
        return 0;
    }
    ~~~~

 */
module Fae.Fae
{
    import Fae.Atomic;
    import Fae.Atomic.Queue;
    import Fae.Atomic.Stack;
    import Fae.Atomic.RingBuffer;
    import Fae.System;
    import Fae.Error;
    import Fae.Graph;
    import Fae.Audio;
    import Fae.Midi;
    // import Fae.Device.File;
    import Fae.Midi.Message;
    import Fae.Plot;
    import Fae.Thread;
    import Fae.Time;
    import Fae.PriorityQueue;
    import Fae.Signal;

    version : () -> List;
    versionString : () -> String;

    initialize : () -> Void;
    terminate : () -> Void;

    // Time.System, Error.Some
    type LogFunc = ((Ptr, System, Error) -> Void)*;

    setLogFile  : FilePath -> Void;
    setLogStd   : () -> Void;
    setLog      : (LogFunc,Ptr) -> Void;

    log             : (Ptr,Error) -> Void;
    logInfo         : (String) -> Void;
    logWarning      : (String) -> Void;
    logError        : (String) -> Void;
    logInfoFrom     : (String,String) -> Void;
    logWarningFrom  : (String,String) -> Void;
    logErrorFrom    : (String,String) -> Void;
    dlog            : (Ptr,Error) -> Void;
    dlogInfo        : (String) -> Void;
}

