
/**
    @addtogroup FaFa

    This modules exports Fa. Example usage:

    ~~~~
    #import <fa/fa.h>

    int main (int argc, char const *argv[])
    {
        fa_fa_initialize();

        ...

        fa_fa_terminate();
        return 0;
    }
    ~~~~

 */
module Fa.Fa
{
    import Fa.Atomic;
    import Fa.Atomic.Queue;
    import Fa.Atomic.Stack;
    import Fa.Atomic.RingBuffer;
    import Fa.System;
    import Fa.Error;
    import Fa.Graph;
    import Fa.Audio;
    import Fa.Midi;
    // import Fa.Device.File;
    import Fa.Midi.Message;
    import Fa.Plot;
    import Fa.Thread;
    import Fa.Time;
    import Fa.PriorityQueue;
    import Fa.Signal;

    version : () -> List;
    versionString : () -> String;

    initialize : () -> Void;
    terminate : () -> Void;

    // Time.System, Error.Some
    type LogFunc = ((Ptr, System, Error) -> Void)*;

    setLogFile  : FilePath -> Void;
    setLogStd   : () -> Void;
    setLog      : (LogFunc,Ptr) -> Void;

    log             : (Ptr,Error) -> Void;
    logInfo         : (String) -> Void;
    logWarning      : (String) -> Void;
    logError        : (String) -> Void;
    logInfoFrom     : (String,String) -> Void;
    logWarningFrom  : (String,String) -> Void;
    logErrorFrom    : (String,String) -> Void;
    dlog            : (Ptr,Error) -> Void;
    dlogInfo        : (String) -> Void;
}

