
/** 
    @addtogroup FaGraph
    
    Immutable directed graph data structure.
    
    @warning
        Not fully implemented.

    @par Literals

    @par Requires 
    - fa_equal_t

    @par Implements 
    - fa_equal_t
    - fa_copy_t
    - fa_destroy_t
    - fa_string_show_t

    @see 
    - [Data structures](@ref DataStructures)
    
 */
module Fa.Graph 
{
    import Fa;
    import Fa.Pair;
    import Fa.List;
    import Fa.String;
    
    type Graph = opaque;
    type Node = Ptr;
    type Edge = Ptr;
    type NodeList = List;
    type EdgeList = List;

    // Constructors
    empty            : () -> Graph;
    insert           : (Node,Graph) -> Graph;
    remove           : (Node,Graph) -> Graph;
    destroy          : Graph -> Void;

    // Edges
    connect          : (Node,Node,Edge,Graph) -> Graph;
    disconnect       : (Node,Node,Graph) -> Graph;

    // Introspection
    // nodes            : Graph -> NodeList;
    // edges            : Graph -> EdgeList;
    // head             : (Edge, Graph) -> Node;
    // tail             : (Edge, Graph) -> Node;
    // from             : (Node, Graph) -> EdgeList;
    // to               : (Node, Graph) -> EdgeList;
    // children         : (Node, Graph) -> NodeList;
    // parents          : (Node, Graph) -> NodeList;

    // Predicates
    // hasNode          : (Node, Graph) -> Bool;
    // hasEdge          : (Edge, Graph) -> Bool;
    // succOf           : (Node, Node, Graph) -> Bool;
    // predOf           : (Node, Node, Graph) -> Bool;
    // directSuccOf     : (Node, Node, Graph) -> Bool;
    // directPredOf     : (Node, Node, Graph) -> Bool;

    toDot            : (String,String,Graph) -> String;

    // Conversions   
    // fromList         : List -> Graph;   // [(e,(n,n))]
    // toList           : Graph -> List;   // [(e,(n,n))]
}

