
/**
    @addtogroup FaMidi

    Real-time midi device.

    @par Sessions, devices and streams implement 
    - fa_destroy_t
    - fa_string_show_t

    @par Devices also implement 
    - fa_equal_t

    @par Streams also implement 
    - fa_message_sender_t
    - fa_message_receiver_t
    
    @see 
    - @ref Devices
 */
module Fa.Midi
{
    import Fa.List;
    import Fa.Pair;
    import Fa.Device;
    import Fa.Error;

    type Device = opaque;
    type Session = opaque;
    type Stream = opaque;
    type SessionCallback = ((Ptr, Session) -> Session)*;
    type StreamCallback = ((Ptr, Stream) -> Stream)*;
    type StatusCallback = Nullary;

    beginSession : () -> Session;
    endSession : Session -> Void;
    withSession : (
        SessionCallback, Ptr, 
        Callback, Ptr) -> Void;

    all : Session -> List;      // [Device]
    default : Session -> Pair;  // (Device,Device)
    defaultInput : Session -> Device;
    defaultOutput : Session -> Device;
    setStatusCallback : (StatusCallback, Ptr, Session) -> Void;

    name : Device -> String;
    hostName : Device -> String;
    hasInput : Device -> Bool;
    hasOutput : Device -> Bool;

    openStream : Device -> Stream;
    closeStream : Stream -> Void;
    withStream : (
        Device, 
        StreamCallback, Ptr, 
        Callback, Ptr
        ) -> Void;
    
    // openAll : Session -> List;  // [Stream]
    // closeAll : Session -> List;  // [Stream]
    // withAll : (Session, StreamsCallback, Ptr, Callback, Ptr) -> Void;  // [Stream]
}

