
/** 
    @addtogroup FaePair
    
    Pair data structure.

    @par Literals
    - `pair(1, 2)`

    @par Implements 
    - fae_equal_t
    - fae_order_t
    - fae_copy_t
    - fae_destroy_t
    - fae_dynamic_t
    - fae_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fae.Pair
{
    import Fae;
    import Fae.List;

    type Pair = opaque;

    create  : (Ptr, Ptr) -> Pair;
    copy   : Pair -> Pair;
    destroy : Pair -> Void;

    first : Pair -> Ptr;
    second : Pair -> Ptr;

    duplicate : Ptr -> Pair;
    swap : Pair -> Pair;
    assoc : Pair -> Pair;    
    unassoc : Pair -> Pair;
    
    toList : Pair -> List;
}

