
/**
    @addtogroup FaPriorityQueue

    Priority queue data structure.

    @par Requires
    - fa_order_t
    @par Implements
    - fa_equal_t
    - fa_string_show_t
    - fa_destroy_t

    @see
    - [Data structures](@ref DataStructures)

 */
module Fa.PriorityQueue
{
    import Fa;

    type PriorityQueue = opaque;

    empty   : () -> PriorityQueue;
    single  : Ptr -> PriorityQueue;
    destroy : PriorityQueue -> Void;

    merge   : (PriorityQueue, PriorityQueue) -> Void;
    insert  : (Ptr, PriorityQueue) -> Void; 
    peek    : PriorityQueue -> Ptr;
    pop     : PriorityQueue -> Ptr;
}

