
/**
    @addtogroup FaePriorityQueue

    Priority queue data structure.

    @par Requires
    - fae_order_t
    @par Implements
    - fae_equal_t
    - fae_string_show_t
    - fae_destroy_t

    @see
    - [Data structures](@ref DataStructures)

 */
module Fae.PriorityQueue
{
    import Fae;

    type PriorityQueue = opaque;

    empty   : () -> PriorityQueue;
    single  : Ptr -> PriorityQueue;
    destroy : PriorityQueue -> Void;

    merge   : (PriorityQueue, PriorityQueue) -> Void;
    insert  : (Ptr, PriorityQueue) -> Void; 
    peek    : PriorityQueue -> Ptr;
    pop     : PriorityQueue -> Ptr;
}

