
/** 
    @addtogroup FaeRatio
    
    Fixed-precision rational numbers.

    @par Literals
    - `ratio(1, 2)`
    - `ratio(0, 1)`
    - `ratio(-1, 2)`

    @par Implements 
    - fae_equal_t
    - fae_order_t
    - fae_string_show_t
    - fae_copy_t
    - fae_destroy_t
    - fae_dynamic_t
    - fae_number_t

 */
module Fae.Ratio 
{
    import Fae.Std;

    type Num    = Int32;
    type Denom  = Int32;
    type Ratio  = opaque;

    create  : (Num, Denom) -> Ratio;
    num     : Ratio -> Num;
    denom   : Ratio -> Denom;
    match   : (Ratio, Num*, Denom*) -> Void;
    copy    : Ratio -> Ratio;
    destroy : Ratio -> Void;
            
    add         : (Ratio, Ratio) -> Ratio;
    subtract    : (Ratio, Ratio) -> Ratio;
    multiply    : (Ratio, Ratio) -> Ratio;
    divide      : (Ratio, Ratio) -> Ratio;
    succ        : Ratio -> Ratio;
    pred        : Ratio -> Ratio;
    negate      : Ratio -> Ratio;
    recip       : Ratio -> Ratio;

    normalize : Ratio -> Ratio;
    toMixed : (Ratio, Num*, Ratio*) -> Void;
}

