
/** 
    @addtogroup FaeSet
    
    Immutable ordered set data structure.


    @par Literals
    - `set(1, 2, 3)`

    @par Display
    - `{1,2,3}`
    
    @par Requires 
    - fae_order_t

    @par Implements 
    - fae_equal_t
    - fae_string_show_t
    - fae_copy_t
    - fae_destroy_t
    - fae_dynamic_t

    @see 
    - [Data structures](@ref DataStructures)
    
 */
module Fae.Set
{
    import Fae;
    import Fae.List;
    import Fae.String;

    type Set = opaque;
    
    // Constructors
    empty            : () -> Set;
    single           : Ptr -> Set;
    add              : (Ptr, Set) -> Set; // add x a = a `union` single x
    set              : (Ptr, Set) -> Set; // set x a = single x `union` a
    remove           : (Ptr, Set) -> Set;
    dadd             : (Ptr, Set) -> Set;
    dset             : (Ptr, Set) -> Set;
    dremove          : (Ptr, Set) -> Set;
    copy             : Set -> Set;
    destroy          : Set -> Void;    

    // Size
    size             : Set -> Int;
    isEmpty          : Set -> Bool;
    isSingle         : Set -> Bool;

    // Predicates
    has              : (Ptr, Set) -> Bool;
    get              : (Ptr, Set) -> Ptr;
    isSubsetOf       : (Set, Set) -> Bool;
    isProperSubsetOf : (Set, Set) -> Bool;

    // Set operations
    sum              : (Set, Set) -> Set; // left biased
    intersection     : (Set, Set) -> Set; // left biased
    difference       : (Set, Set) -> Set;
    product          : (Set, Set) -> Set;
    power            : Set -> Set;

    // Conversions   
    fromList         : List -> Set;
    toList           : Set -> List;
}

