
/**
    @addtogroup FaeSignal
    
    Provides signals.
    
 */
module Fae.Signal
{
    import Fae;    
    import Fae.Pair;
    import Fae.Type;
    import Fae.Time;
    
    type Signal = opaque;

    typeOf : Signal -> Type;


    constant            : Ptr              -> Signal; // a             -> S a
    identity            : ()               -> Signal; //                  S a -> S b
    apply               : (Signal, Signal) -> Signal; //                  S (a -> b) -> S a -> S b
    lift                : (Unary,   Ptr)   -> Signal; // (a -> b)      -> S a -> S b
    lift2               : (Binary,  Ptr)   -> Signal; // (a -> b -> c) -> S a -> S b -> S c
    lift3               : (Ternary, Ptr)   -> Signal; // ...

    time                : () -> Signal;              //                   S Time
    delay               : (Time, Signal)  -> Signal; // Time           -> S a -> S a
    fix                 : (((Ptr, Signal) -> Signal)*, Ptr) -> Signal; // (S a -> S a) -> S a

    // debug
    run :               (Signal, Unary, Ptr) -> Void;
    

    add                 : () -> Signal;
    subtract            : () -> Signal;
    multiply            : () -> Signal;
    power               : () -> Signal;
    divide              : () -> Signal;
    modulo              : () -> Signal;
    absolute            : () -> Signal;

    not                 : () -> Signal;
    and                 : () -> Signal;
    or                  : () -> Signal;
    xor                 : () -> Signal;
    bitNot              : () -> Signal;
    bitAnd              : () -> Signal;
    bitOr               : () -> Signal;
    bitXor              : () -> Signal;
    shiftLeft           : () -> Signal;
    shiftRight          : () -> Signal;

    equal               : () -> Signal;
    lessThan            : () -> Signal;
    greaterThan         : () -> Signal;
    lessThanEqual       : () -> Signal;
    greaterThanEqual    : () -> Signal;

    acos                : () -> Signal;
    asin                : () -> Signal;
    atan                : () -> Signal;
    cos                 : () -> Signal;
    sin                 : () -> Signal;
    tan                 : () -> Signal;
    exp                 : () -> Signal;
    log                 : () -> Signal;
    log10               : () -> Signal;
    pow                 : () -> Signal;
    sqrt                : () -> Signal;
    abs                 : () -> Signal;
    min                 : () -> Signal;
    max                 : () -> Signal;
    fmod                : () -> Signal;
    remainder           : () -> Signal;
    floor               : () -> Signal;
    ceil                : () -> Signal;
    rint                : () -> Signal;
}

