
/** 
    Actions on control values.

    @par Literals

    @par Implements 
    - fa_copy_t
    - fa_destroy_t
    - fa_string_show_t

    @see 

 */
module Fa.Action
{
    import Fa;
    import Fa.Pair;
    import Fa.List;
    import Fa.Signal;

    type Action = opaque;
    type Channel = Int;
    type Name = String;

    set : (Channel, Double) -> Action;
    accum : (Channel, UnaryDouble, Ptr) -> Action;
    send : (Name, Ptr) -> Action;

    copy : Action -> Action;
    destroy : Action -> Void;
}

