
/**
    @addtogroup FaAtomic

    Mutable atomic references.

    @par Literals
    - `atomic()`

    @par Implements
    - fa_equal_t
    - fa_order_t
    - fa_copy_t
    - fa_destroy_t
    - fa_string_show_t

    @see
    - [Data structures](@ref DataStructures)
 */
module Fa.Atomic
{
    import Fa;
    import Fa.Std;

    type Atomic = opaque;

    create  : () -> Atomic;
    copy    : Atomic -> Atomic;
    swap    : (Atomic, Atomic) -> Void;
    destroy : Atomic -> Void;

    exchange : (Atomic, Ptr, Ptr) -> Bool;
    get     : Atomic -> Ptr;
    set     : (Atomic, Ptr) -> Void;
    modify  : (Atomic, Unary, Ptr) -> Void;

    // TODO increment : (Atomic, Int32) -> Void;
}

