
/**
    @addtogroup FaAudio

    Real-time audio devices. These device run processors on the input and output
    the underlying system, typically physical audio interfaces. A running audio
    computation is represented by a *stream*. Access to the current device setups
    is provided by *sessions*.

    @par Sessions implement
    - fa_equal_t
    - fa_destroy_t
    - fa_string_show_t

    @par Devices implement
    - fa_equal_t
    - fa_string_show_t

    Devices implement [Equal](@ref fa_equal_t) and [Show](@ref fa_string_show_t),
    but now destroy, as they are always managed by the underlying session.

    @par Streams implement
    - fa_time_clock_t
    - fa_message_sender_t
    - fa_message_receiver_t
    - fa_destroy_t
    - fa_string_show_t

    Stream implements [Clock](@ref fa_time_clock_t) by counting the number
    of processed samples. Precision is usually limited to the current frame size.

    Stream also implements [SenderInterface](@ref fa_message_sender_t) and
    [ReceiverInterface](@ref fa_message_sender_t), dispatching messages to the underlying
    processor network. The address of a processor can be obtained by @ref fa_processor_address.


    @see
    - @ref Devices
 */
module Fa.Audio
{
    import Fa.List;
    import Fa.Pair;
    import Fa.Device;
    import Fa.Error;
    import Fa.Type;

    type Session = opaque;
    type Device  = opaque;
    type Stream  = opaque;
    type SessionCallback = ((Ptr, Session) -> Session)*;
    type StreamCallback = ((Ptr, Stream) -> Stream)*;
    type StatusCallback = Nullary;

    beginSession : () -> Session;
    endSession : Session -> Void;
    withSession : (
        SessionCallback, Ptr,
        Callback, Ptr) -> Void;

    all : Session -> List;      // [Device]
    default : Session -> Pair;  // (Device,Device)
    defaultInput : Session -> Device;
    defaultOutput : Session -> Device;
    setStatusCallback : (StatusCallback, Ptr, Session) -> Void;

    name : Device -> String;
    hostName : Device -> String;
    hasInput : Device -> Bool;
    hasOutput : Device -> Bool;
    inputType : Device -> Type;
    outputType : Device -> Type;

    openStream : (Device, Ptr, Device) -> Stream;
    closeStream : Stream -> Void;
    withStream : (
        Device, Ptr, Device,
        StreamCallback, Ptr,
        Callback, Ptr
        ) -> Void;

}

