
/** 
    @addtogroup FaBuffer
    
    Mutable buffers. 
    
    Each buffer is a mutable sequence of bytes with single-ownership
    semantics. The length of a buffer can never change, but its memory can be reused using the destructive
    resize operation.
    
    Note that buffers are not collections as their contents are mutable.


    @par Literals
    - `buffer(size)` 

    @par Implements 
    - fa_copy_t
    - fa_destroy_t
    - fa_string_show_t

    @see 
    - [Data structures](@ref DataStructures)
 */
module Fa.Buffer
{
    import Fa;
    import Fa.Std;
    import Fa.Pair;
    import Fa.String;
    import Fa.Type;

    /** @typedef fa_buffer_t
        The buffer. 
     */
    type Buffer = opaque;

    /** Create a new buffer.
        @note
            O(n)
     */
    create  : (Size) -> Buffer;
    /** Create a buffer wrapping the given memory region.

        @param ptr  Pointer to wrap.
        @param size Number of bytes to wrap.
        @param destroy_function Function to call upon destruction (optional).
        @param destroy_data Data closed over by the destroy function.
        @note
            O(1)
     */
    wrap    : (Ptr, Size, Unary, Ptr) -> Buffer;
    /** Copy the given buffer.
        @note
            O(n)
     */
    copy    : Buffer -> Buffer;
    /** Copy the given buffer using the given size.
        @note
            O(n)
     */
    resize  : (Size, Buffer) -> Buffer;
    /** Destroy the given buffer.
        @note
            O(n)
     */
    destroy : Buffer -> Void;

    /** Return the size of the buffer.
        @note
            O(1)
     */
    size    : Buffer -> Size;  
    /** Read a value from the buffer.
        @note
            O(1)
     */
    get     : (Buffer, Size) -> UInt8;
    /** Update a value in the buffer.
        @note
            O(1)
     */
    set     : (Buffer, Size, UInt8) -> Void;

    getInt16  : (Buffer, Size) -> Int16;
    getInt32  : (Buffer, Size) -> Int32;
    getInt64  : (Buffer, Size) -> Int64;
    getFloat  : (Buffer, Size) -> Float;
    getDouble : (Buffer, Size) -> Double;

    setInt16  : (Buffer, Size, Int16) -> Void;
    setInt32  : (Buffer, Size, Int32) -> Void;
    setInt64  : (Buffer, Size, Int64) -> Void;    
    setFloat  : (Buffer, Size, Float) -> Void;
    setDouble : (Buffer, Size, Double) -> Void;    


    // Input / Output
    readRaw     : String -> Buffer;
    writeRaw    : (String,Buffer) -> Void;    
    
    /**
        Reads an audio file.

        @returns
            A pair $$type, buffer)$$.
     */
    readAudio   : String -> Pair; // (Type,Buffer)
    writeAudio  : (String,Type,Buffer) -> Void;

    /** Return the address of the buffer.

        This function is unsafe as it provides access to the buffer contents without
        ownership semantics.
        @note
            O(1)
     */
    unsafeAddress : Buffer -> Void*;
}

