
/** 

 */
module Fa.Pair
{
    import Fa;
    import Fa.List;

    type Closure = opaque;

    /**
        @param function
            Function to run when closure is applied.
            First argument is the data pointer.
        @param destroy_function                     
            Function to run when closure is destroyed.
            The argument is the data pointer.
        @param data
            Data pointer passed to the enclosed functions when applied.
     */
    create : (Binary, Unary, Ptr) -> Closure;
    destroy : Closure -> Void;
    compose : (Closure, Closure) -> Closure;
    dcompose : (Closure, Closure) -> Closure;
}

