
/**
    @addtogroup FaList

    Immutable list data structure.

    - Fast front access: ([empty](@ref fa_list_empty), 
                          [single](@ref fa_list_single), 
                          [cons](@ref fa_list_cons), 
                          [head](@ref fa_list_head), 
                          [tail](@ref fa_list_tail)).

    - Slow back access ([init](@ref fa_list_init), 
                        [last](@ref fa_list_last)).

    - Slow random access ([index](@ref fa_list_index), 
                          [insert](@ref fa_list_insert), 
                          [remove](@ref fa_list_remove)).

    - Slow range access: ([take](@ref fa_list_take), 
                          [drop](@ref fa_list_drop), 
                          [range](@ref fa_list_range), 
                          [insertRange](@ref fa_list_insert_range), 
                          [removeRange](@ref fa_list_remove_range))

    - Linear [find](@ref fa_list_find), 
             [map](@ref fa_list_map), 
             [fold](@ref fa_list_fold), 
             [reverse](@ref fa_list_reverse) and 
             [filter](@ref fa_list_filter).

    - Logarithmic [sort](@ref fa_list_sort).

    @par Literals
    - `list(1, 2, 3)`

    @par Display
    - `[1,2,3]`
    
    @par Iteration
    ~~~
    fa_list_for_each (list(1,2,3), x)
    {
        fa_print("%s\n", x);
    }
    ~~~

    @par Implements
    - fa_equal_t
    - fa_order_t
    - fa_copy_t
    - fa_destroy_t
    - fa_dynamic_t
    - fa_string_show_t

    @see
    - [Data structures](@ref DataStructures)

 */
module Fa.List
{
    import Fa;

    type List   = opaque;

    // Constructors
    empty       : () -> List;
    single      : Ptr -> List;
    cons        : (Ptr, List) -> List;
    dcons       : (Ptr, List) -> List;
    repeat      : (Int, Ptr) -> List;
    enumerate   : (Int, Int) -> List;
    copy        : List -> List;
    destroy     : List -> Void;

    // Predicates
    isEmpty     : List -> Bool;
    isSingle    : List -> Bool;
    length      : List -> Int;

    // Sequential access
    head        : List -> Ptr;
    tail        : List -> List;
    dtail       : List -> List;
    init        : List -> List;
    dinit       : List -> List;
    last        : List -> Ptr;

    // Misc operations
    append      : (List, List) -> List;
    dappend     : (List, List) -> List;
    reverse     : List -> List;
    dreverse    : List -> List;
    sort        : List -> List;
    dsort       : List -> List;

    // Random access
    take         : (Int, List) -> List;
    dtake        : (Int, List) -> List;
    drop         : (Int, List) -> List;
    ddrop        : (Int, List) -> List;
    index        : (Int, List) -> Ptr;
    range        : (Int, Int, List) -> List;
    insert       : (Int, Ptr, List) -> List;
    dinsert      : (Int, Ptr, List) -> List;
    insertRange  : (Int, List, List) -> List;
    dinsertRange : (Int, List, List) -> List;
    remove       : (Int, List) -> List;
    dremove      : (Int, List) -> List;
    removeRange  : (Int, Int, List) -> List;
    dremoveRange : (Int, Int, List) -> List;

    // Searching
    has         : (Ptr, List) -> Bool;
    find        : (Pred, Ptr, List) -> Ptr;
    indexOf     : (Ptr, List) -> Int;
    findIndex   : (Pred, Ptr, List) -> Int;

    // Maps and folds
    filter      : (Pred, Ptr, List) -> List;
    dfilter     : (Pred, Ptr, List) -> List;
    map         : (Unary, Ptr, List) -> List;
    dmap        : (Unary, Ptr, List) -> List;
    joinMap     : (Unary, Ptr, List) -> List;
    djoinMap    : (Unary, Ptr, List) -> List;
    join        : List -> List;
    djoin       : List -> List;

    foldLeft    : (Binary, Ptr, Ptr, List) -> Ptr;
    dfoldLeft   : (Binary, Ptr, Ptr, List) -> Ptr;

    // Conversions
    toList      : List -> List;
}

