
/** 

Basic options parser.
    
Example:

~~~
fa_option_t options[] = {
    { "h", "help",            "Show help info",             fa_option_parse_string },
    { "x", "value-with-def",  "Show help info",             fa_option_parse_int    },
    { "n", "number-of-cores", "Number of cores\n                                   "
                              "Very interesting parameter", fa_option_parse_int    }
};

int main(int argc, char const *argv[])
{
    fa_option_show_all(
        options,
        "Usage: fa_options\n"
        "       fa_options [FILES]\n"
        );
                
    fa_unpair(
        fa_option_parse_all(options, argc, (char**) argv), 
        options,
        arguments
        ) 
    {
        fa_print_ln(options);   // {"foo": 1, "bar": 2}
        fa_print_ln(arguments); // [1,2,3]
    }
}
~~~    
    
 */
module Fa.Option
{
    import Fa;
    import Fa.Std;
    import Fa.String;
    import Fa.Pair;

    type Option = struct {
        shortName   : Char*,
        longName    : Char*,
        description : Char*,
        parser      : (Char * -> Ptr)*
    };

    
    /** Parse options according to the given specification (see example above).
        
        @returns
            A pair where the first component is a @ref fa_map_t of `(name, value)`
            pairs, and the second component is a list of remaning arguments.    
    */
    parse   : (Int, Option*, Int, Char**) -> Pair;
    
    /** Show options according to the given specification (see example above) on the standard output.
     */
    show    : (Int, Option*, Char*) -> Void;

    parseInt       : (Char *)            -> Ptr;
    parseFloat     : (Char *)            -> Ptr;
    parseDouble    : (Char *)            -> Ptr;
    parseString    : (Char *)            -> Ptr;
    parseFail      : (Char *)            -> Ptr;    
}