
/** 
    @addtogroup FaPair
    
    Immutable pair data structure.

    @par Literals
    - `pair(1, 2)`

    @par Implements 
    - fa_equal_t
    - fa_order_t
    - fa_copy_t
    - fa_destroy_t
    - fa_dynamic_t
    - fa_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fa.Pair
{
    import Fa;
    import Fa.List;

    type Pair = opaque;
    type Struct = struct { first : Ptr, second : Ptr };

    create  : (Ptr, Ptr) -> Pair;
    read : (Struct*) -> Pair;
    write : (Struct*, Pair) -> Void;
    copy   : Pair -> Pair;
    destroy : Pair -> Void;

    first : Pair -> Ptr;
    second : Pair -> Ptr;

    duplicate : Ptr -> Pair;
    swap : Pair -> Pair;
    assoc : Pair -> Pair;    
    unassoc : Pair -> Pair;
    
    toList : Pair -> List;
}

