
/** 
    @addtogroup FaRatio
    
    Fixed-precision rational numbers.

    @par Literals
    - `ratio(1, 2)`
    - `ratio(0, 1)`
    - `ratio(-1, 2)`

    @par Implements 
    - fa_equal_t
    - fa_order_t
    - fa_string_show_t
    - fa_copy_t
    - fa_destroy_t
    - fa_dynamic_t
    - fa_number_t

 */
module Fa.Ratio 
{
    import Fa.Std;

    type Num    = Int32;
    type Denom  = Int32;
    type Ratio  = opaque;

    create  : (Num, Denom) -> Ratio;
    num     : Ratio -> Num;
    denom   : Ratio -> Denom;
    match   : (Ratio, Num*, Denom*) -> Void;
    copy    : Ratio -> Ratio;
    destroy : Ratio -> Void;
            
    add         : (Ratio, Ratio) -> Ratio;
    subtract    : (Ratio, Ratio) -> Ratio;
    multiply    : (Ratio, Ratio) -> Ratio;
    divide      : (Ratio, Ratio) -> Ratio;
    succ        : Ratio -> Ratio;
    pred        : Ratio -> Ratio;
    negate      : Ratio -> Ratio;
    recip       : Ratio -> Ratio;

    normalize : Ratio -> Ratio;
    toMixed : (Ratio, Num*, Ratio*) -> Void;
}

