
/**
    Provides task scheduling.

    @par Implements 
    - fa_equal_t
    - fa_string_show_t
    - fa_destroy_t
    
 */
module Fa.Scheduler
{
    import Fa;
    import Fa.Time;

    type Scheduler = opaque;

    create   : Clock -> Scheduler; // Requires Clock
    destroy  : Scheduler -> Void;
    
    schedule : (Scheduler, Ptr) -> Void;
    execute  : Scheduler -> Void;
    loop     : Scheduler -> Void;
    loopFor  : (Time, Scheduler) -> Void;
    
    // Loop until finished
    // run      : Scheduler -> Void;
}

