
/**
    @addtogroup FaSignal
    
    Provides signals.
    
 */
module Fa.Signal
{
    import Fa;    
    import Fa.Pair;
    import Fa.Type;
    import Fa.Time;
    
    type Signal = opaque;

    /** Like fa_unary_t, but speficied on signals.
    */
    type UnarySignal    = ((Ptr, Signal) -> Signal)*;

    /** Like fa_unary_t, but speficied on doubles.
    */
    type UnaryDouble    = ((Ptr, Double) -> Double)*;

    /** Like fa_binary_t, but speficied on doubles.
    */
    type BinaryDouble   = ((Ptr, Double, Double) -> Double)*;


    time        : () -> Signal;
    random      : () -> Signal;
    constant    : Double -> Signal;
    lift        : ( String -> UnaryDouble, Ptr, Signal )          -> Signal;
    lift2       : ( String -> BinaryDouble, Ptr, Signal, Signal ) -> Signal;
    loop        : ( UnarySignal, Ptr )                            -> Signal;
    delay       : ( Int, Signal )                                 -> Signal;
    input       : ( Int )                                         -> Signal;
    output      : ( Int, Int, Signal )                            -> Signal;

    add                 : (Signal, Signal) -> Signal;
    subtract            : (Signal, Signal) -> Signal;
    multiply            : (Signal, Signal) -> Signal;
    power               : (Signal, Signal) -> Signal;
    divide              : (Signal, Signal) -> Signal;
    modulo              : (Signal, Signal) -> Signal;
    absolute            : (Signal, Signal) -> Signal;

    not                 : () -> Signal;
    and                 : (Signal, Signal) -> Signal;
    or                  : (Signal, Signal) -> Signal;
    xor                 : (Signal, Signal) -> Signal;
    bitNot              : (Signal, Signal) -> Signal;
    bitAnd              : (Signal, Signal) -> Signal;
    bitOr               : (Signal, Signal) -> Signal;
    bitXor              : (Signal, Signal) -> Signal;
    shiftLeft           : (Signal, Signal) -> Signal;
    shiftRight          : (Signal, Signal) -> Signal;

    equal               : (Signal, Signal) -> Signal;
    lessThan            : (Signal, Signal) -> Signal;
    greaterThan         : (Signal, Signal) -> Signal;
    lessThanEqual       : (Signal, Signal) -> Signal;
    greaterThanEqual    : (Signal, Signal) -> Signal;

    acos                : (Signal, Signal) -> Signal;
    asin                : (Signal, Signal) -> Signal;
    atan                : (Signal, Signal) -> Signal;
    cos                 : (Signal, Signal) -> Signal;
    sin                 : (Signal, Signal) -> Signal;
    tan                 : (Signal, Signal) -> Signal;
    exp                 : (Signal, Signal) -> Signal;
    log                 : (Signal, Signal) -> Signal;
    log10               : (Signal, Signal) -> Signal;
    pow                 : (Signal, Signal) -> Signal;
    sqrt                : (Signal, Signal) -> Signal;
    abs                 : (Signal, Signal) -> Signal;
    min                 : (Signal, Signal) -> Signal;
    max                 : (Signal, Signal) -> Signal;
    fmod                : (Signal, Signal) -> Signal;
    remainder           : (Signal, Signal) -> Signal;
    floor               : (Signal, Signal) -> Signal;
    ceil                : (Signal, Signal) -> Signal;
    rint                : (Signal, Signal) -> Signal;    

    isVariable : Signal -> Bool;
    isConstant : Signal -> Bool;
    areConstant : List -> Bool; // [Signal]
    signalNodeCount : Signal -> Int;
    // signalTree : Signal -> Tree String;
    requiredInputs : Signal -> Int;
    requiredBuses : Signal -> Int;
    requiredDelay : Signal -> Int;
    // optimize : Signal -> Signal;
    // optimize1 : Signal -> Signal;
    simplify : Signal -> Signal;

    latter : (Signal, Signal) -> Signal;
    former : (Signal, Signal) -> Signal;
    impulse : () -> Signal;
    line : Double -> Signal;
    lowPass : (Signal, Signal, Signal, Signal, Signal) -> Signal;
    biquad : (Signal, Signal, Signal, Signal, Signal, Signal) -> Signal;

}

