
/**
    Provides external streams.
    
    - *Sources* produce sequences of data (bytes, characters, floats etc)
    - *Sinks* consume sequences of data (bytes, characters, floats etc)
    - Both *sources* and *sinks* accepts external buffers.
    
    @since
        2.9
 */
module Fa.Io
{
    import Fa;
    import Fa.Buffer;
    import Fa.Atomic.RingBuffer;

    /** Callback to receive data.
    
        Argument is either a (possibly empty) buffer, meaning that more data is to arrive,
        or `NULL`, indicating that the data source has been extinguished.
     */
    type BufferCallback = (Buffer -> Void)*;

    type FilterInterface = struct {
        pull : (Ptr, Source, BufferCallback) -> Void
    };

    /** Implements the filter interface. */
    type Filter = opaque;
    /** Implements the filter interface (ignores the source). */
    type Source = opaque;

    /** Filter two filterable things.
     */
    filter : (Ptr, Ptr) -> Ptr;
}

