
/**
    @addtogroup FaThread

    Cross-platform threads.

    We provide threads and mutexes. For non-blocking constructs, see the @ref FaAtomic modules.

    @par Literals
    - `thread(function, data)`

    @par Implements 
    - fa_equal_t  (Thread only)
    - fa_order_t  (Thread only)
    - fa_string_show_t (both)
    - fa_destroy_t (Mutex only)
    
    Threads do not implement destroy, use join or detach instead.
    
 */
module Fa.Thread
{
    import Fa;
    import Fa.Std;

    type Thread = opaque;
    type Mutex = opaque;
    type Milliseconds = Int;

    create  : (Nullary, Ptr) -> Thread;
    sleep   : Milliseconds -> Void;
    join    : Thread -> Void;
    detach  : Thread -> Void;
    main    : () -> Thread;
    current : () -> Thread;

    createMutex     : () -> Mutex;
    destroyMutex    : Mutex -> Void;
    lock            : Mutex -> Bool;
    tryLock         : Mutex -> Bool;
    unlock          : Mutex -> Bool;
}

