
/** 
    Provides real-time midi input and output.
    @author     Hans Höglund
 */
module Doremir.Audio.Device.MidiDevice
{
    type Session = Intptr;
    type MidiDevice = Intptr;
    type Stream = Intptr;
    type MidiDeviceList = List;

    beginSession : () -> Session;
    endSession   : (Session) -> Void;

    devices     : (Session) -> MidiDeviceList;
    standard    : (Session) -> MidiDevicePair;
    openStream  : (MidiDevice, Proc) -> Stream;
    closeStream : (Stream) -> Void;
}