
/** 
    Provides real-time midi input and output.

    @defgroup   DoremirAudioDeviceMidi Devices: Midi
    @author     Hans Höglund
 */
module Doremir.Audio.Device.Midi
{
    type Session = Intptr;
    type Device = Intptr;
    type Stream = Intptr;
    type DeviceList = List;

    beginSession : () -> Session;
    endSession   : (Session) -> Void;

    devices         : (Session) -> DeviceList;
    standardDevices : (Session) -> DevicePair;
    openStream      : (Device, Proc) -> Stream;
    closeStream     : (Stream) -> Void;
}