
/** 
    @addtogroup DoremirProcessorDelay
    
    @par Implements 
        doremir_destroy_t
        doremir_dispatcher_t
        doremir_processor_t
        doremir_string_show_t
    @see 
        \ref Processors
 */
module Doremir.Processor.Delay
{
    import Doremir;
    import Doremir.Processor;
    
    type Proc = opaque;    
    create : (Type, Size) -> Proc;
    destroy : Proc -> Void;
}

