(in-package :doremir)
(define-foreign-type thread-future-type () () (:actual-type :pointer))
(define-parse-method thread-future () (make-instance 'thread-future-type))
(defclass thread-future () ((thread-future-ptr :initarg :thread-future-ptr)))
(defmethod translate-to-foreign (x (type thread-future-type)) (slot-value x 'thread-future-ptr))
(defmethod translate-from-foreign (x (type thread-future-type)) (make-instance 'thread-future :thread-future-ptr x))
(defctype thread-future-value ptr)
(defcfun (thread-future-create "doremir_thread_future_create") thread-future (a nullary) (b ptr))
(defcfun (thread-future-destroy "doremir_thread_future_destroy") :void (a thread-future))
(defcfun (thread-future-is-done "doremir_thread_future_is_done") :boolean (a thread-future))
(defcfun (thread-future-wait "doremir_thread_future_wait") :void (a thread-future))
(defcfun (thread-future-get "doremir_thread_future_get") thread-future-value (a thread-future))