(in-package :audio-engine)
(define-foreign-type thread-improving-type () () (:actual-type :pointer))
(define-parse-method thread-improving () (make-instance 'thread-improving-type))
(defclass thread-improving () ((thread-improving-ptr :initarg :thread-improving-ptr)))
(defmethod translate-to-foreign (x (type thread-improving-type)) (slot-value x 'thread-improving-ptr))
(defmethod translate-from-foreign (x (type thread-improving-type)) (make-instance 'thread-improving :thread-improving-ptr x))
(defctype thread-improving-value ptr)
(defcfun (thread-improving-create "doremir_thread_improving_create") thread-improving)
(defcfun (thread-improving-destroy "doremir_thread_improving_destroy") :void (a thread-improving))
(defcfun (thread-improving-is-done "doremir_thread_improving_is_done") :boolean (a thread-improving))
(defcfun (thread-improving-wait "doremir_thread_improving_wait") :void (a thread-improving))
(defcfun (thread-improving-get "doremir_thread_improving_get") thread-improving-value (a thread-improving))