
/**
    @addtogroup FaSystemDirectory
    
    Cross-platform directory utilities.    
 */

module Fa.System.Directory
{
    import Fa;
    import Fa.String;
    type FilePath = String;

    home : () -> FilePath;
    current : () -> FilePath;
    create : FilePath -> Void;
    remove : FilePath -> Void;          
    // TODO isFile : FilePath -> Bool
    // TODO isDirectory : FilePath -> Bool
    // TODO enumerate : FilePath -> [FilePath]

    readFile : FilePath -> String;
    writeFile : (FilePath,String) -> Void;
    appendFile : (FilePath,String) -> Void;
}

