
/**
    @addtogroup FaeDeviceMidi

    Real-time midi device.

    @par Sessions, devices and streams implement 
    - fae_destroy_t
    - fae_string_show_t

    @par Devices also implement 
    - fae_equal_t

    @par Streams also implement 
    - fae_message_sender_t
    - fae_message_receiver_t
    
    @see 
    - @ref Devices
 */
module Fae.Device.Midi
{
    import Fae.List;
    import Fae.Pair;
    import Fae.Device;
    import Fae.Error;
    import Fae.Event;

    type Session = opaque;
    type Stream = opaque;
    type SessionCallback = ((Ptr, Session) -> Session)*;
    type StreamCallback = ((Ptr, Stream) -> Stream)*;
    type StatusCallback = Nullary;

    beginSession : () -> Session;
    endSession : Session -> Void;
    withSession : (
        SessionCallback, Ptr, 
        Callback, Ptr) -> Void;

    all : Session -> List;      // [Midi]
    default : Session -> Pair;  // (Midi,Midi)
    defaultInput : Session -> Midi;
    defaultOutput : Session -> Midi;
    setStatusCallback : (StatusCallback, Ptr, Session) -> Void;

    name : Midi -> String;
    hostName : Midi -> String;
    hasInput : Midi -> Bool;
    hasOutput : Midi -> Bool;

    openStream : Midi -> Stream;
    closeStream : Stream -> Void;
    withStream : (
        Midi, 
        StreamCallback, Ptr, 
        Callback, Ptr
        ) -> Void;
    
    // openAll : Session -> List;  // [Stream]
    // closeAll : Session -> List;  // [Stream]
    // withAll : (Session, StreamsCallback, Ptr, Callback, Ptr) -> Void;  // [Stream]
}

