
/** 
    @addtogroup FaAtomicRingBuffer
    
    A byte-level, bounded lock-free queue.
    
    This structure is called a buffer for historical reasons, it is more accurately
    a queue and does not support random accces.
    
    @warning
        Not fully implemented.
        

    @par Literals
    - `atomic_ring_buffer(size)` 

    @par Implements 
    - fa_destroy_t
    - fa_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fa.Atomic.RingBuffer
{            
    import Fa;
    
    type RingBuffer = opaque;

    create : Size -> RingBuffer;
    copy : RingBuffer -> RingBuffer;
    resize : (Size, RingBuffer) -> RingBuffer;
    swap : (RingBuffer, RingBuffer) -> Void;
    destroy : RingBuffer -> Void;

    size : RingBuffer -> Size;  
    read : RingBuffer -> UInt8;
    write : (RingBuffer, UInt8) -> Bool;
}

