
/** 
    A byte-level, bounded lock-free queue.
    
    This structure is called a buffer for historical reasons, it is more accurately
    a queue and does not support random accces.
    
    @warning
        Not fully implemented.
        

    @par Literals
    - `atomic_ring_buffer(size)` 

    @par Implements 
    - fa_destroy_t
    - fa_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fa.Atomic.RingBuffer
{            
    import Fa;
    
    type RingBuffer = opaque;

    create : Size -> RingBuffer;
    destroy : RingBuffer -> Void;

    size : RingBuffer -> Size;  

    close : RingBuffer -> Void;
    isClosed : RingBuffer -> Bool;
    canRead : (RingBuffer, Size) -> Bool;
    canWrite : (RingBuffer, Size) -> Bool;

    read        : (RingBuffer, UInt8*) -> Bool;
    readFloat   : (RingBuffer, Float*) -> Bool;
    readDouble  : (RingBuffer, Double*) -> Bool;

    write       : (RingBuffer, UInt8) -> Bool;
    writeFloat  : (RingBuffer, Float) -> Bool;
    writeDouble : (RingBuffer, Double) -> Bool;
}

