
/** 
    @addtogroup FaAtomicStack
    
    Mutable atomic (lock-free) stacks.

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fa.Atomic.Stack
{
    import Fa;

    type Stack = opaque;
    
    /** Create a new stack.
        @par Atomicity
            Non-atomic
     */
    create : () -> Stack;
    /** Destroy the given stack.
        @par Atomicity
            Non-atomic
     */
    destroy : Stack -> Void;
    
    /** Read a value from the given stack.
        @return
            A value (optional).
        @par Atomicity
            Atomic
     */
    read : Stack -> Ptr;
    /** Write the given value to the given stack.
        @param stackr   Queue.
        @param value    Value to write (optional).
        @par Atomicity
            Atomic
     */
    write : (Stack, Ptr) -> Bool;
}

