(in-package :doremir)
(defctype atomic-queue :pointer)
(defcfun (atomic-queue-create "doremir_atomic_queue_create") atomic-queue)
(defcfun (atomic-queue-destroy "doremir_atomic_queue_destroy") :void (a atomic-queue))
(defcfun (atomic-queue-read "doremir_atomic_queue_read") ptr (a atomic-queue))
(defcfun (atomic-queue-write "doremir_atomic_queue_write") :boolean (a atomic-queue) (b ptr))