
/**
    @addtogroup DoremirAudioEngineDeviceAudio
    
    Real-time audio device.
    
 */
module Doremir.AudioEngine.Device.Audio
{
    import Doremir.List;
    import Doremir.Pair;

    type Session = opaque;
    type Device = opaque;
    type Stream = opaque;

    beginSession : () -> Session;
    endSession : Session -> Void;

    devices : Session -> List;
    standard : Session -> Pair;
    closeStream : Stream -> Void;
    // openStream : (Audio, Proc) -> Stream;
}