
/**
    Provides an atomic circular buffer
    @defgroup DoremirAtomicRingBuffer Concurrency: Atomic ringbuffer
 */
module Doremir.Atomic.RingBuffer
{
    type RingBuffer = Intptr;

    create : (RingBuffer) -> RingBuffer;
    copy : (RingBuffer) -> RingBuffer;
    swap : (RingBuffer, RingBuffer) -> Void;
    destroy : (RingBuffer) -> Void;

    read : (RingBuffer) -> Intptr;
    write : (RingBuffer, Intptr) -> Intptr;
}

