
/** 
    Provides real-time audio input and output.
    @author     Hans Höglund
 */
module Doremir.Audio.Device.AudioDevice
{
    type AudioDevice = Intptr;
    type Session = Intptr;
    type Stream = Intptr;
    type AudioDeviceList = List;

    beginSession : () -> Session;
    endSession   : (Session) -> Void;

    devices     : (Session) -> AudioDeviceList;
    standard    : (Session) -> AudioDevicePair;
    openStream  : (AudioDevice, Proc) -> Stream;
    closeStream : (Stream) -> Void;
}