
/** 
    Provides real-time audio input and output.
    @author     Hans Höglund
 */
module Doremir.Audio.Device.AudioDevice
{
    import Doremir.List;
    import Doremir.Pair;
    
    type Session = opaque;
    type AudioDevice = opaque;
    type Stream = opaque;

    beginSession : () -> Session;
    endSession   : Session -> Void;

    devices     : Session -> List;
    standard    : Session -> Pair;
    // openStream  : (AudioDevice, Proc) -> Stream;
    closeStream : Stream -> Void;
}