
/** 
    Provides non-real-time audio input and output.
    @author     Hans Höglund
 */
module Doremir.Audio.Device.FileDevice
{                       
    import Doremir.String;
    
    type FileDevice = opaque;
    type Stream = opaque;

    create      : (FilePath, FilePath) -> FileDevice;
    destroy     : (FileDevice) -> Void;
    // openStream  : (FileDevice, Proc) -> Stream;
    closeStream : (Stream) -> Void;
}