
/**
    @addtogroup FaeThreadImproving
    
    Improving values.
    
 */
module Fae.Thread.Improving
{
    import Fae.Std;
    import Fae.Thread;

    type Improving = opaque;
    type Value  = Ptr;

    // TODO obtain result from what?
    create  : () -> Improving;
    destroy : Improving -> Void;
    
    isDone : Improving -> Bool;
    wait   : Improving -> Void;
    get    : Improving -> Value;    
}

