
/**
    @addtogroup DoremirDeviceAudio
    
    Real-time audio device.
    
 */
module Doremir.Device.Audio
{
    import Doremir.List;
    import Doremir.Pair;
    import Doremir.Processor;

    type Audio = opaque;

    type Session = opaque;
    type Stream = opaque;

    type SessionCallback = (Session -> Session)*;
    withSession : (SessionCallback) -> Void;
    beginSession : () -> Session;
    endSession : Session -> Void;
                                                           
    type StreamCallback = (Stream -> Stream)*;
    withStream : (Audio, Processor, Audio, StreamCallback) -> Void;
    startStream : (Audio, Processor, Audio) -> Stream;
    stopStream : Stream -> Void;
    
    all : Session -> List;
    default : Session -> Pair;
    
}