
/**
    @addtogroup DoremirDeviceMidi

    Real-time midi device.

    @par Sessions, devices and streams implement 
    - doremir_destroy_t
    - doremir_string_show_t

    @par Devices also implement 
    - doremir_equal_t

    @par Streams also implement 
    - doremir_message_sender_t
    - doremir_message_receiver_t
    
    @see 
    - @ref Devices
 */
module Doremir.Device.Midi
{
    import Doremir.List;
    import Doremir.Pair;
    import Doremir.Message;
    import Doremir.Processor;

    type DeviceMidi = opaque;  // TODO call Device
    type Session = opaque;
    type Stream = opaque;

    all : Session -> List;      // [DeviceMidi]
    default : Session -> Pair;  // (DeviceMidi,DeviceMidi)

    name : DeviceMidi -> String;
    hostName : DeviceMidi -> String;
    hasInput : DeviceMidi -> Bool;
    hasOutput : DeviceMidi -> Bool;

    beginSession : () -> Session;
    restartSession : Session -> Session;
    endSession : Session -> Void;

    startStream : DeviceMidi -> Stream;
    restartStream : Stream -> Stream;
    stopStream : Stream -> Void;

    type SessionCallback = (Session -> Session)*;
    type StreamCallback = (Stream -> Stream)*;
    withSession : SessionCallback -> Void;
    withStream : (DeviceMidi, StreamCallback) -> Void;
}

