(in-package :faudio)
(define-foreign-type atomic-type () () (:actual-type :pointer))
(define-parse-method atomic () (make-instance 'atomic-type))
(defclass atomic () ((atomic-ptr :initarg :atomic-ptr)))
(defmethod translate-to-foreign (x (type atomic-type)) (slot-value x 'atomic-ptr))
(defmethod translate-from-foreign (x (type atomic-type)) (make-instance 'atomic :atomic-ptr x))
(defcfun (atomic-create "fa_atomic_create") atomic)
(defcfun (atomic-copy "fa_atomic_copy") atomic (a atomic))
(defcfun (atomic-destroy "fa_atomic_destroy") :void (a atomic))
(defcfun (atomic-exchange "fa_atomic_exchange") :boolean (a atomic) (b ptr) (c ptr))
(defcfun (atomic-get "fa_atomic_get") ptr (a atomic))
(defcfun (atomic-modify "fa_atomic_modify") :void (a atomic) (b unary) (c ptr))
(defcfun (atomic-set "fa_atomic_set") :void (a atomic) (b ptr))

