(in-package :faudio)
(defctype clock-interface (:pointer :void))
(define-foreign-type clock-type () () (:actual-type :pointer))
(define-parse-method clock () (make-instance 'clock-type))
(defclass clock () ((clock-ptr :initarg :clock-ptr)))
(defmethod translate-to-foreign (x (type clock-type)) (slot-value x 'clock-ptr))
(defmethod translate-from-foreign (x (type clock-type)) (make-instance 'clock :clock-ptr x))
(defcfun (clock-time "fa_clock_time") time (a clock))
(defcfun (clock-milliseconds "fa_clock_milliseconds") time-milliseconds (a clock))
(defcfun (clock-standard "fa_clock_standard") clock)

