(in-package :faudio)
(defctype error-severity :int)
(defctype error-interface (:pointer :void))
(define-foreign-type error-type () () (:actual-type :pointer))
(define-parse-method error () (make-instance 'error-type))
(defclass error () ((error-ptr :initarg :error-ptr)))
(defmethod translate-to-foreign (x (type error-type)) (slot-value x 'error-ptr))
(defmethod translate-from-foreign (x (type error-type)) (make-instance 'error :error-ptr x))
(defcfun (error-check "fa_error_check") :boolean (a ptr))
(defcfun (error-log "fa_error_log") :void (a ptr) (b error))
(defcfun (error-severity "fa_error_severity") error-severity (a error))
(defcfun (error-message "fa_error_message") string (a error))
(defcfun (error-origin "fa_error_origin") string (a error))
(defcfun (error-format "fa_error_format") string (a :boolean) (b error))
(defctype error-callback (:pointer (:pointer :void)))
(defcfun (error-create-simple "fa_error_create_simple") error (a error-severity) (b string) (c string))

