(in-package :faudio)
; (defctype ptr (:pointer :void))
(defctype nullary (:pointer (:pointer :void)))
(defctype unary (:pointer (:pointer :void)))
(defctype binary (:pointer (:pointer :void)))
(defctype ternary (:pointer (:pointer :void)))
(defctype pred (:pointer (:pointer :void)))
(defctype char8 :char)
(defctype char16 :uint16)
(defctype char32 :uint32)
(defcfun (is-bool "fa_is_bool") :boolean (a ptr))
(defcfun (is-int8 "fa_is_int8") :boolean (a ptr))
(defcfun (is-int16 "fa_is_int16") :boolean (a ptr))
(defcfun (is-int32 "fa_is_int32") :boolean (a ptr))
(defcfun (is-int64 "fa_is_int64") :boolean (a ptr))
(defcfun (is-float "fa_is_float") :boolean (a ptr))
(defcfun (is-double "fa_is_double") :boolean (a ptr))
(defcfun (is-ref "fa_is_ref") :boolean (a ptr))
(defcfun (to-bool "fa_to_bool") :boolean (a ptr))
(defcfun (to-int8 "fa_to_int8") :int8 (a ptr))
(defcfun (to-int16 "fa_to_int16") :int16 (a ptr))
(defcfun (to-int32 "fa_to_int32") :int32 (a ptr))
(defcfun (to-int64 "fa_to_int64") :int64 (a ptr))
(defcfun (to-float "fa_to_float") :float (a ptr))
(defcfun (to-double "fa_to_double") :double (a ptr))
(defcfun (peek-bool "fa_peek_bool") :boolean (a ptr))
(defcfun (peek-int8 "fa_peek_int8") :int8 (a ptr))
(defcfun (peek-int16 "fa_peek_int16") :int16 (a ptr))
(defcfun (peek-int32 "fa_peek_int32") :int32 (a ptr))
(defcfun (peek-int64 "fa_peek_int64") :int64 (a ptr))
(defcfun (peek-float "fa_peek_float") :float (a ptr))
(defcfun (peek-double "fa_peek_double") :double (a ptr))
(defcfun (from-bool "fa_from_bool") ptr (a :boolean))
(defcfun (from-int8 "fa_from_int8") ptr (a :int8))
(defcfun (from-int16 "fa_from_int16") ptr (a :int16))
(defcfun (from-int32 "fa_from_int32") ptr (a :int32))
(defcfun (from-int64 "fa_from_int64") ptr (a :int64))
(defcfun (from-float "fa_from_float") ptr (a :float))
(defcfun (from-double "fa_from_double") ptr (a :double))
(defctype id :int64)
(defctype impl (:pointer (:pointer :void)))
(defcfun (interface "fa_interface") ptr (a id) (b ptr))
(defctype equal (:pointer :void))
(defcfun (equal "fa_equal") :boolean (a ptr) (b ptr))
(defcfun (not-equal "fa_not_equal") :boolean (a ptr) (b ptr))
(defctype order (:pointer :void))
(defcfun (less-than "fa_less_than") :boolean (a ptr) (b ptr))
(defcfun (greater-than "fa_greater_than") :boolean (a ptr) (b ptr))
(defcfun (less-than-equal "fa_less_than_equal") :boolean (a ptr) (b ptr))
(defcfun (greater-than-equal "fa_greater_than_equal") :boolean (a ptr) (b ptr))
(defcfun (min "fa_min") ptr (a ptr) (b ptr))
(defcfun (max "fa_max") ptr (a ptr) (b ptr))
(defctype number (:pointer :void))
(defcfun (add "fa_add") ptr (a ptr) (b ptr))
(defcfun (subtract "fa_subtract") ptr (a ptr) (b ptr))
(defcfun (multiply "fa_multiply") ptr (a ptr) (b ptr))
(defcfun (divide "fa_divide") ptr (a ptr) (b ptr))
(defcfun (absolute "fa_absolute") ptr (a ptr))
(defcfun (dadd "fa_dadd") ptr (a ptr) (b ptr))
(defcfun (dsubtract "fa_dsubtract") ptr (a ptr) (b ptr))
(defcfun (dmultiply "fa_dmultiply") ptr (a ptr) (b ptr))
(defcfun (ddivide "fa_ddivide") ptr (a ptr) (b ptr))
(defcfun (dabsolute "fa_dabsolute") ptr (a ptr))
(defctype copy (:pointer :void))
(defctype destroy (:pointer :void))
(defcfun (copy "fa_copy") ptr (a ptr))
(defcfun (move "fa_move") ptr (a ptr))
(defcfun (destroy "fa_destroy") :void (a ptr))
(defcfun (check "fa_check") :boolean (a ptr))
(defcfun (print "fa_print") :void (a (:pointer :char)) (b ptr))
(defcfun (dprint "fa_dprint") :void (a (:pointer :char)) (b ptr))
(defcfun (print-ln "fa_print_ln") :void (a ptr))
(defcfun (dprint-ln "fa_dprint_ln") :void (a ptr))

