
/** 
    @addtogroup FaAtomicQueue
    
    Mutable atomic (lock-free) queues.

    @par Literals
    - `atomic_queue()` 

    @par Implements 
    - fa_destroy_t
    - fa_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fa.Atomic.Queue
{
    import Fa;
    
    type Queue = opaque;
    
    create : () -> Queue;
    destroy : Queue -> Void;
    
    read : Queue -> Ptr;
    write : (Queue, Ptr) -> Bool;
}

