
/** 
    @addtogroup FaeAtomicQueue
    
    Mutable atomic (lock-free) queues.

    @par Literals
    - `atomic_queue()` 

    @par Implements 
    - fae_destroy_t
    - fae_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fae.Atomic.Queue
{
    import Fae;
    
    type Queue = opaque;
    
    create : () -> Queue;
    destroy : Queue -> Void;
    
    read : Queue -> Ptr;
    write : (Queue, Ptr) -> Bool;
}

