(in-package :cl-user)
(define-foreign-type atomic-type () () (:actual-type :pointer))
(define-parse-method atomic () (make-instance 'atomic-type))
(defclass atomic () ((atomic-ptr :initarg :atomic-ptr)))
(defmethod translate-to-foreign (x (type atomic-type)) (slot-value x 'atomic-ptr))
(defmethod translate-from-foreign (x (type atomic-type)) (make-instance 'atomic :atomic-ptr x))
(defcfun (atomic-create "fae_atomic_create") atomic)
(defcfun (atomic-copy "fae_atomic_copy") atomic (a atomic))
(defcfun (atomic-swap "fae_atomic_swap") :void (a atomic) (b atomic))
(defcfun (atomic-destroy "fae_atomic_destroy") :void (a atomic))
(defcfun (atomic-exchange "fae_atomic_exchange") :boolean (a atomic) (b ptr) (c ptr))
(defcfun (atomic-get "fae_atomic_get") ptr (a atomic))
(defcfun (atomic-set "fae_atomic_set") :void (a atomic) (b ptr))
(defcfun (atomic-modify "fae_atomic_modify") :void (a atomic) (b unary) (c ptr))