(in-package :cl-user)
(defctype dynamic-type-repr :int)
(defctype dynamic (:pointer :void))
(defcfun (dynamic-check "fae_dynamic_check") :boolean (a ptr))
(defcfun (dynamic-get-type "fae_dynamic_get_type") dynamic-type-repr (a ptr))