(in-package :faudio)
(defctype system-event-type :int)
(defcfun (system-event-mouse-move "fa_system_event_mouse_move") event)
(defcfun (system-event-mouse-drag "fa_system_event_mouse_drag") event)
(defcfun (system-event-mouse-up "fa_system_event_mouse_up") event)
(defcfun (system-event-mouse-down "fa_system_event_mouse_down") event)
(defcfun (system-event-key-up "fa_system_event_key_up") event)
(defcfun (system-event-key-down "fa_system_event_key_down") event)
(defcfun (system-event-select "fa_system_event_select") event (a list))
(defcfun (system-event-receive "fa_system_event_receive") message-sender (a list))
(defcfun (system-event-write-std "fa_system_event_write_std") event (a event))
(defcfun (system-event-send-std "fa_system_event_send_std") message-receiver)
(defcfun (system-event-write-log "fa_system_event_write_log") event (a event))
(defcfun (system-event-send-log "fa_system_event_send_log") message-receiver)

