
/**
    @addtogroup FaSystemDirectory
    
    Cross-platform directory utilities.    
 */

module Fa.System.Directory
{
    import Fa;
    import Fa.String;

    home : () -> String;
    current : () -> String;
    create : String -> Void;
    remove : String -> Void;          
    // TODO isFile : String -> Bool
    // TODO isDirectory : String -> Bool
    // TODO enumerate : String -> [String]

    readFile : String -> String;
    writeFile : (String,String) -> Void;
    appendFile : (String,String) -> Void;
}

