
/**
    @addtogroup FaSystemEvent

    Provides mouse and keyboard events.

    @note
        On OS X we can not get keyboard events unless 'Access for assistive devices'
        is enabled in System Preferences. Mouse events should work either way.

 */

module Fa.System.Event
{
    import Fa;
    import Fa.Message;
    import Fa.Event;
    import Fa.String;

    type Type = enum {
        MouseMoveEvent,
        MouseDragEvent,
        MouseUpEvent,
        MouseDownEvent,
        KeyUpEvent,
        KeyDownEvent
    };

    mouseMove    : () -> Event;         // (Float, Float)
    mouseDrag    : () -> Event;
    mouseUp      : () -> Event;
    mouseDown    : () -> Event;
    keyUp        : () -> Event;         // [KeyCode, Char, String]
    keyDown      : () -> Event;
    select       : List -> Event;       // Event [Int16/Type]
    receive      : List -> Sender;      // Sender [Int16/Type]

    // readStd      : Event;                               // Event String
    // receiveStd   : Sender;                              // Sender String
    writeStd     : Event -> Event;                      // Event String -> Event ()
    sendStd      : () -> Receiver;                      // Receiver String
    writeLog     : Event -> Event;                      // Event String -> Event ()
    sendLog      : () -> Receiver;                      // Receiver String

    // readHandle    : Handle -> Event;                    // Event String
    // writeHandle   : (Handle, Event)  -> Event;          // Event String -> Event ()
    // receiveHandle : Handle -> Sender;                   // Sender String
    // sendHandle    : Handle -> Receiver;                 // Receiver String
    
    // readFile      : FilePath -> Event;                  // Event String
    // writeFile     : (FilePath, Event)  -> Event;        // Event String -> Event ()
    // receiveFile   : FilePath -> Sender;                 // Sender String
    // sendFile      : FilePath -> Receiver;               // Receiver String
}

