
/** 
    Provides lifting of binary functions into audio processors.

    ### Associated types

    Kind           | Type
    -------------- | --------------------------
    State          | `()`
    Argument       | `()`
    Result         | `()`
    Input          | `(a,b)`
    Output         | `c`

    @author     Hans Höglund
 */
module Doremir.Audio.Processor.Binary
{
    type Func = Intptr;
    type Proc = Intptr;    
    lift : Func -> Proc;
}