
/** 
    @addtogroup DoremirAtomicQueue
    
    Lock-free queue (FIFO) data structure.

    @par Literals
    - `atomic_queue()` 

    @par Implements 
    - doremir_destroy_t
    - doremir_string_show_t
 */
module Doremir.Atomic.Queue
{
    import Doremir;
    
    type Queue = opaque;
    
    create : () -> Queue;
    destroy : Queue -> Void;
    
    read : Queue -> Ptr;
    write : (Queue, Ptr) -> Bool;
}

