
/** 
    @addtogroup DoremirAtomicRingBuffer
    
    Circular buffer data structure.
    
    Note that while this structure is called a \ref DoremirBuffer, it does not support random access.

    @par Literals
    - `atomic_ring_buffer()` 

    @par Implements 
    - doremir_destroy_t
    - doremir_string_show_t
 */
module Doremir.Atomic.RingBuffer
{            
    import Doremir;
    
    type RingBuffer = opaque;

    create : Size -> RingBuffer;
    copy : RingBuffer -> RingBuffer;
    resize : (Size, RingBuffer) -> RingBuffer;
    swap : (RingBuffer, RingBuffer) -> Void;
    destroy : RingBuffer -> Void;

    size : RingBuffer -> Size;  
    read : RingBuffer -> UInt8;
    write : (RingBuffer, UInt8) -> Bool;
}

