
/** 
    @addtogroup DoremirAtomicRingBuffer
    
    A byte-level, bounded atomic queue.
    
    This structure is called a buffer for historical reasons, it is more accurately
    a queue and does not support random accces.

    @par Literals
    - `atomic_ring_buffer()` 

    @par Implements 
    - doremir_destroy_t
    - doremir_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Doremir.Atomic.RingBuffer
{            
    import Doremir;
    
    type RingBuffer = opaque;

    create : Size -> RingBuffer;
    copy : RingBuffer -> RingBuffer;
    resize : (Size, RingBuffer) -> RingBuffer;
    swap : (RingBuffer, RingBuffer) -> Void;
    destroy : RingBuffer -> Void;

    size : RingBuffer -> Size;  
    read : RingBuffer -> UInt8;
    write : (RingBuffer, UInt8) -> Bool;
}

