
/** 
    @addtogroup DoremirAtomicRingBuffer
    
    Circular buffer data structure.
    
    Note that while this structure is called a \ref DoremirBuffer, it does not support random access.
 */
module Doremir.Atomic.RingBuffer
{
    type RingBuffer = opaque;

    create : RingBuffer -> RingBuffer;
    copy : RingBuffer -> RingBuffer;
    swap : (RingBuffer, RingBuffer) -> Void;
    destroy : RingBuffer -> Void;

    read : RingBuffer -> UInt8;
    write : (RingBuffer, UInt8) -> Void;
}

