
/**
    @addtogroup DoremirAudioEngineScheduler
    
    Provides task scheduling.
    
 */
module Doremir.AudioEngine.Scheduler
{
    import Doremir.Thread.Improving;

    type Time = Int; // TODO
    type Action = (() -> Void)*; // TODO

    /** @interface doremir_audio_engine_scheduler_t */
    type Scheduler = struct {
        schedule : ((Time, Action) -> Void)*,
        execute : (() -> Void)*
    };

    create : Improving -> Scheduler;
    destroy : Scheduler -> Void;
    swap : (Scheduler, Scheduler) -> Void;
}