
/** 
    @addtogroup FaeMessage
    
    Immutable representation of Midi messages.

    @par Literals
    - `midi(note_on, 60, 127)`
    - `midi(note_off, 60, 127)`
    - `midi(0x9, 60, 127)`
    - `midi_sysex(buffer)`

    @par Implements 
    - fae_equal_t
    - fae_order_t
    - fae_string_show_t
    - fae_copy_t
    - fae_destroy_t
    - fae_dynamic_t
    
 */
module Fae.Midi.Message
{
    import Fae.Std;
    import Fae.Pair;
    import Fae.Buffer;
    
    type Status = enum {
        NoteOff,
        NoteOn,
        AfterTouch,
        ControlChange,
        ProgramChange,
        ChannelPressure,
        PitchWheel,
        Sysex 
    };     

    type Channel = Int;    
    type Data    = Int;    
    type Message = opaque;

    createSimple  : (Status, Int, Int) -> Message;
    createSysex   : Buffer -> Message;
    copy          : Message -> Message;
    destroy       : Message -> Void;

    status        : Message -> Status;
    channel       : Message -> Channel;

    isSimple      : Message -> Bool;
    simpleData    : Message -> Pair;
    isSysex       : Message -> Bool;
    sysexData     : Message -> Buffer;    
}

