(in-package :audio-engine)
(define-foreign-type device-buffer-type () () (:actual-type :pointer))
(define-parse-method device-buffer () (make-instance 'device-buffer-type))
(defclass device-buffer () ((device-buffer-ptr :initarg :device-buffer-ptr)))
(defmethod translate-to-foreign (x (type device-buffer-type)) (slot-value x 'device-buffer-ptr))
(defmethod translate-from-foreign (x (type device-buffer-type)) (make-instance 'device-buffer :device-buffer-ptr x))
(define-foreign-type device-buffer-stream-type () () (:actual-type :pointer))
(define-parse-method device-buffer-stream () (make-instance 'device-buffer-stream-type))
(defclass device-buffer-stream () ((device-buffer-stream-ptr :initarg :device-buffer-stream-ptr)))
(defmethod translate-to-foreign (x (type device-buffer-stream-type)) (slot-value x 'device-buffer-stream-ptr))
(defmethod translate-from-foreign (x (type device-buffer-stream-type)) (make-instance 'device-buffer-stream :device-buffer-stream-ptr x))
(defcfun (device-buffer-create "doremir_device_buffer_create") device-buffer (a :int32))
(defcfun (device-buffer-destroy "doremir_device_buffer_destroy") :void (a device-buffer))
(defcfun (device-buffer-run "doremir_device_buffer_run") :void (a device-buffer) (b processor) (c device-buffer))