(in-package :doremir)
(defctype device-buffer :pointer)
(defctype device-buffer-stream :pointer)
(defcfun (device-buffer-create "doremir_device_buffer_create") device-buffer (a :int32))
(defcfun (device-buffer-destroy "doremir_device_buffer_destroy") :void (a device-buffer))