(in-package :doremir)
(defctype device-file :pointer)
(defctype device-file-stream :pointer)
(defcfun (device-file-create "doremir_device_file_create") device-file (a string-file-path) (b string-file-path))
(defcfun (device-file-destroy "doremir_device_file_destroy") :void (a device-file))
(defcfun (device-file-close-stream "doremir_device_file_close_stream") :void (a device-file-stream))