(in-package :doremir)
(define-foreign-type device-file-type () () (:actual-type :pointer))
(define-parse-method device-file () (make-instance 'device-file-type))
(defclass device-file () ((device-file-ptr :initarg :device-file-ptr)))
(defmethod translate-to-foreign (x (type device-file-type)) (slot-value x 'device-file-ptr))
(defmethod translate-from-foreign (x (type device-file-type)) (make-instance 'device-file :device-file-ptr x))
(define-foreign-type device-file-stream-type () () (:actual-type :pointer))
(define-parse-method device-file-stream () (make-instance 'device-file-stream-type))
(defclass device-file-stream () ((device-file-stream-ptr :initarg :device-file-stream-ptr)))
(defmethod translate-to-foreign (x (type device-file-stream-type)) (slot-value x 'device-file-stream-ptr))
(defmethod translate-from-foreign (x (type device-file-stream-type)) (make-instance 'device-file-stream :device-file-stream-ptr x))
(defcfun (device-file-create "doremir_device_file_create") device-file (a string-file-path))
(defcfun (device-file-destroy "doremir_device_file_destroy") :void (a device-file))
(defcfun (device-file-run "doremir_device_file_run") :void (a device-file) (b processor) (c device-file))