
/** 
    Immutable left-leaning pair data structure.
    
    This type is identical to @ref fa_pair_t, except that it compares on the first element.
    Useful for ordered lists etc.

    @par Literals
    - `pair_left(1, 2)`

    @par Implements 
    - fa_equal_t
    - fa_order_t
    - fa_copy_t
    - fa_destroy_t
    - fa_string_show_t

    @see 
    - [Data structures](@ref DataStructures)

 */
module Fa.Pair.Left
{
    import Fa;
    import Fa.Pair;
    import Fa.List;

    type Left = opaque;
    type Struct = struct { first : Ptr, second : Ptr };

    create  : (Ptr, Ptr) -> Left;
    read : (Struct*) -> Left;
    write : (Struct*, Left) -> Void;
    copy   : Left -> Left;
    destroy : Left -> Void;
    decons : (Ptr*, Ptr*, Left) -> Void;
    
    toPair   : Left -> Pair;
    fromPair : Pair -> Left;

    toList : Left -> List;
}

