#!/bin/bash
pushd external_libraries/portaudio;

./configure --prefix=`pwd`/result \
		&& make install \
		&& cp -R include/ result/include/

popd;                                                 

# Windows:
# 	./configure --with-winapi=wasapi,asio --with-asiodir=../asio/ASIOSDK2/
# 	make
# 	ls lib/.libs