(in-package :audio-engine)
(defctype system-event-type :int)
(defcfun (system-event-mouse-move "doremir_system_event_mouse_move") event)
(defcfun (system-event-mouse-drag "doremir_system_event_mouse_drag") event)
(defcfun (system-event-mouse-up "doremir_system_event_mouse_up") event)
(defcfun (system-event-mouse-down "doremir_system_event_mouse_down") event)
(defcfun (system-event-key-up "doremir_system_event_key_up") event)
(defcfun (system-event-key-down "doremir_system_event_key_down") event)
(defcfun (system-event-select "doremir_system_event_select") event (a list))
(defcfun (system-event-receive "doremir_system_event_receive") message-sender (a list))
(defcfun (system-event-write-std "doremir_system_event_write_std") event (a event))
(defcfun (system-event-send-std "doremir_system_event_send_std") message-receiver)
(defcfun (system-event-write-log "doremir_system_event_write_log") event (a event))
(defcfun (system-event-send-log "doremir_system_event_send_log") message-receiver)