
/**
    @addtogroup DoremirSystemDirectory
    
    Cross-platform directory utilities.    
 */

module Doremir.System.Directory
{
    import Doremir;
    import Doremir.String;

    home : () -> FilePath;
    current : () -> FilePath;
    create : FilePath -> Void;
    remove : FilePath -> Void;          
    // isFile : FilePath -> Bool
    // isDirectory : FilePath -> Bool
    // enumerate : FilePath -> [FilePath]

    readFile : FilePath -> String;
    writeFile : (FilePath,String) -> Void;
    appendFile : (FilePath,String) -> Void;
}