
/**
    @addtogroup DoremirSystemEvent

    Provides mouse and keyboard events.

    @note
        On OS X we can not get keyboard events unless 'Access for assistive devices'
        is enabled in System Preferences. Mouse events should work either way.

 */

module Doremir.System.Event
{
    import Doremir;
    import Doremir.Message;
    import Doremir.Event;
    import Doremir.String;

    type Type = enum {
        MouseMoveEvent,
        MouseDragEvent,
        MouseUpEvent,
        MouseDownEvent,
        KeyUpEvent,
        KeyDownEvent
    };


    mouseMove    : () -> Event;     // (Float, Float)
    mouseDrag    : () -> Event;
    mouseUp      : () -> Event;
    mouseDown    : () -> Event;
    keyUp        : () -> Event;     // [KeyCode, Char, String]
    keyDown      : () -> Event;
    select       : List -> Event;   // Event [Int16/EventType]
    selectSend   : List -> Sender;  // Sender [Int16/EventType]

    // readFile     : FilePath -> Event;              // Event String
    // writeFile    : (FilePath, Event)  -> Event;    // Event String -> Event ()
    // sendFileSend : FilePath -> Sender;              // Sender String
    // readFileRecv : FilePath -> Receiver;            // Receiver String
    

}

