
/**
    @addtogroup DoremirSystemEvent

    Provides mouse and keyboard events.

    @note
        On OS X we can not get keyboard events unless 'Access for assistive devices'
        is enabled in System Preferences. Mouse events should work either way.

 */

module Doremir.System.Event
{
    import Doremir;
    import Doremir.Message;
    import Doremir.Event;
    import Doremir.String;

    type Source = enum {
        MouseMoveEvent,
        MouseDragEvent,
        MouseUpEvent,
        MouseDownEvent,
        KeyUpEvent,
        KeyDownEvent
    };

    mouseMove    : () -> Event;                     // (Float, Float)
    mouseDrag    : () -> Event;
    mouseUp      : () -> Event;
    mouseDown    : () -> Event;
    keyUp        : () -> Event;                     // [KeyCode, Char, String]
    keyDown      : () -> Event;
    select       : List -> Event;                   // Event [Int16/Source]
    send         : List -> Sender;                  // Sender [Int16/Source]

    // readStd      : Event;                           // Event String
    // readStdSend  : Sender;                          // Sender String
    writeStd     : Event -> Event;                  // Event String -> Event ()
    recvStd      : () -> Receiver;                  // Receiver String

    // readHandle  : Handle -> Event;                    // Event String
    // writeHandle : (Handle, Event)  -> Event;          // Event String -> Event ()
    // sendHandle  : Handle -> Sender;                   // Sender String
    // recvHandle  : Handle -> Receiver;                 // Receiver String
    // 
    // readFile   : FilePath -> Event;               // Event String
    // writeFile  : (FilePath, Event)  -> Event;     // Event String -> Event ()
    // sendFile   : FilePath -> Sender;              // Sender String
    // recvFile   : FilePath -> Receiver;            // Receiver String

}

