
/**
    @addtogroup DoremirSystemEvent
    
    Provides mouse and keyboard events.    
 */

module Doremir.System.Event
{
    import Doremir;
    import Doremir.Message;
    import Doremir.Event;
    import Doremir.String;

    type Type = enum {
        MouseMoveEvent,
        MouseDragEvent,
        MouseUpEvent,
        MouseDownEvent,
        KeyUpEvent,
        KeyDownEvent
    };              
    
    getSender : List -> SomeSender; // [Int16/EventType] -> Dispatcher
    getEvent : List -> Event; // [Int16/EventType] -> Event
}