
/**
    @addtogroup DoremirThreadFuture
    
    Future values.
    
 */
module Doremir.Thread.Future
{
    import Doremir.Std;
    import Doremir.Thread;

    type Future = opaque;
    type Value  = Ptr;

    // TODO obtain result from what?
    create  : (Nullary, Ptr) -> Future;
    destroy : Future -> Void;
    
    isDone : Future -> Bool;
    wait   : Future -> Void;
    get    : Future -> Value;    
}

