
/**
    @addtogroup DoremirThreadImproving
    
    Improving values.
    
 */
module Doremir.Thread.Improving
{
    import Doremir.Std;
    import Doremir.Thread;

    type Improving = opaque;
    type Value  = Intptr;

    // TODO obtain result from what?
    create  : () -> Improving;
    destroy : Improving -> Void;
    
    isDone : Improving -> Bool;
    wait   : Improving -> Void;
    get    : Improving -> Value;    
}

